Checking for Anagram
Algo-Phantoms/Algo-Tree pull request #1020
Opened 2021-03-15 05:08 UTC by prateek-jpg

Have solved the issue in java. Please let me know if any changes required.
#395 fixed

2021-03-15 05:08 UTC, prateek-jpg commented
@tarun26091999 Have solved the issue.

2021-04-05 03:50 UTC, raksha009 requested changes

2021-04-05 03:50 UTC, raksha009 commented on Code/Java/Anagram.java
> +/*Two strings are said to be an Anagram if all the characters of a string are equal and have same frequency but arranged in different order.
Write /*  
at line 1

2021-04-05 03:50 UTC, raksha009 commented on Code/Java/Anagram.java
> +		String s=sc.next();
Add spaces around the operators like =, < , > etc

2021-04-05 03:50 UTC, raksha009 commented on Code/Java/Anagram.java
> +		String s1=sc.next();
```suggestion
		String s1 = sc.next();
```

2021-04-05 03:50 UTC, raksha009 commented on Code/Java/Anagram.java
> +		int l1=s.length(),l2=s1.length(); // storing the length of both the strings
Add comments above the line

2021-04-05 03:50 UTC, raksha009 commented on Code/Java/Anagram.java
> +				s1=s1+ch;
```suggestion
				s1=s1 + ch;
```

2021-04-05 03:50 UTC, raksha009 commented on Code/Java/Anagram.java
> +      Time Complexity-O(nlog n)
Specify n

2021-04-05 03:50 UTC, raksha009 commented on Code/Java/Anagram.java
> +/*  OUTPUT
```suggestion
/*  
Test Cases
```

2021-04-05 03:50 UTC, raksha009 commented on Code/Java/Anagram.java
> +    1. Enter string 1-prateek
```suggestion
    Input:  Enter string 1-prateek
```

2021-04-05 03:50 UTC, raksha009 commented on Code/Java/Anagram.java
> +       OUTPUT-Two strings are Anagram
```suggestion
       Output:  Two strings are Anagram
```

2021-04-14 10:19 UTC, raksha009 requested changes

2021-04-14 10:19 UTC, raksha009 commented on Code/Java/Anagram.java
> +			System.out.println("OUTPUT:Two strings are not Anagram");
```suggestion
			System.out.println("Two strings are not Anagram"); 
```

2021-04-14 10:19 UTC, raksha009 commented on Code/Java/Anagram.java
> +				System.out.println("OUTPUT:Two strings are Anagram");
Hey, we do not have to display "OUTPUT" on the console, its just a part of documentation when we add test cases after our code in the file.

2021-04-14 10:19 UTC, raksha009 commented on Code/Java/Anagram.java
> +				System.out.println("OUTPUT:Two strings are not Anagram");
```suggestion
				System.out.println("Two strings are not Anagram");
```

2021-04-14 10:19 UTC, raksha009 commented on Code/Java/Anagram.java
> +             OUTPUT
Test cases
Input: 
Output: 

Also plz align properly.

2021-04-14 10:19 UTC, raksha009 commented on Code/Java/Anagram.java
> +      Time Complexity-O(nlog n)
Do this chnge too.

2021-04-14 10:19 UTC, raksha009 commented on Code/Java/Anagram.java
> +      where n: size of the input
n cannot be size of input. Its is length of / no of our something depending on our problem statement

2021-04-19 08:58 UTC, raksha009 requested changes

2021-04-19 08:58 UTC, raksha009 commented on Code/Java/Anagram.java
> +             OUTPUT
Test cases
Input:
Output:

Also plz align properly.

Make this change

2021-04-19 08:58 UTC, raksha009 commented on string/readme.md
> +* Reverse a string ---->[C++](/Code/C++/reverse_string.cpp)
Plz have a look of what changes have you done via Files changed option and make changes appropriately.

2021-05-07 15:57 UTC, rudrakshi99 commented
PLease resolve merge conflicts.

2021-06-07 15:51 UTC, raksha009 approved these changes

2021-06-07 15:52 UTC, raksha009 commented
There are conflicts that can't be resolved by us but only participants.
This being the case, closing the PR as no more commits are allowed.

2021-06-07 15:52 UTC, closed without merging