Sudoku Solver
Algo-Phantoms/Algo-Tree pull request #1073
Opened 2021-03-16 04:51 UTC by Akash20x

This pull request closes #176

Solution of sudoku solver in python

2021-03-17 09:10 UTC, plazzy99 requested changes
Update the readme file for the same

2021-03-17 09:10 UTC, plazzy99 commented on Code/Python/Sudoku_Solver.py
> +# Link: https://leetcode.com/problems/sudoku-solver/
we need an appropriate description of the issue.
Links are not supposed to be added.

2021-03-17 09:10 UTC, plazzy99 commented on Code/Python/Sudoku_Solver.py
> +board = [["5","3",".",".","7",".",".",".","."],
not clear

2021-03-17 09:10 UTC, plazzy99 commented on Code/Python/Sudoku_Solver.py
> +solution.solveSudoku(board)
2 test cases and space and time complexity need to be added here in the bottom

2021-03-21 07:59 UTC, Akash20x commented
Please check my pull request

2021-03-27 15:46 UTC, closed without merging