Spiral Traversal of Binary Tree
Algo-Phantoms/Algo-Tree pull request #1087
Opened 2021-03-16 11:55 UTC by tk315

Kindly check it out and do the needful.
Thanks!

Fixed #853

2021-03-25 16:53 UTC, rudrakshi99 requested changes

2021-03-25 16:53 UTC, rudrakshi99 commented on Code/C++/spiral_traversal_of_binary_tree.cpp
> +struct Node {
use `class` instead of `struct`.

2021-03-25 16:53 UTC, rudrakshi99 commented on Code/C++/spiral_traversal_of_binary_tree.cpp
> +    root -> left = new Node(2);
Make it user input by using  `loop` to insert the data.

2021-03-25 16:54 UTC, rudrakshi99 commented
also use `nullptr` instead of `NULL`

2021-03-26 03:18 UTC, tk315 commented
All the required changes done.
Kindly review it.

2021-03-29 15:37 UTC, rudrakshi99 approved these changes

2021-03-29 15:46 UTC, rudrakshi99 commented
@tk315 update the list in the tree folder.

2021-03-30 01:03 UTC, tk315 commented
@rudrakshi99 Already done

2021-03-30 20:50 UTC, tk315 commented on Code/C++/spiral_traversal_of_binary_tree.cpp
> +1 5 7 4 6 2 3
Requested Changes done

2021-03-31 06:55 UTC, rudrakshi99 commented
Please resolve merge conflicts.

2021-03-31 09:12 UTC, OjusWiZard approved these changes
Looks good to me

2021-04-02 14:29 UTC, merged