Longest Increasing Subsequence code
Algo-Phantoms/Algo-Tree pull request #1115
Opened 2021-03-17 07:23 UTC by Chirag018

Fixes #528 
Adding LIS code in java

2021-03-17 16:12 UTC, raksha009 requested changes

2021-03-17 16:12 UTC, raksha009 commented on Algorithm/DP/longest_increasing_subsequence.java
> +        int my_arr[] = { 10,9,2,5,3,7,101,18 };
Take input from user.

2021-03-17 16:12 UTC, raksha009 commented on Algorithm/DP/longest_increasing_subsequence.java
> +// Space Complexity is O(n)
Specify what is n

2021-03-17 16:12 UTC, raksha009 commented on Algorithm/DP/longest_increasing_subsequence.java
> +
Add 2 test cases here.

2021-03-17 17:00 UTC, Chirag018 reviewed
Updated Successfully

2021-03-18 07:07 UTC, raksha009 commented
Plz go through the guidelines and link yr code with respective folder.

2021-03-18 13:07 UTC, Chirag018 commented
Okay

2021-03-18 20:08 UTC, raksha009 commented
Plz close this pr if its a duplicate one.

2021-03-19 16:40 UTC, closed without merging