Added Largest rectangle
Algo-Phantoms/Algo-Tree pull request #1160
Opened 2021-03-18 16:17 UTC by sudipg4112001

### Related issue:
Fixes#161 

Added the code in C++, the folder stack

2021-03-19 01:59 UTC, krishna-NIT requested changes
@sudipg4112001  **Really Appreciate your work within time,**
do few changes to make it more understandable
_Add Description at starting &
Add test case/output time and space complexity at Last
add necessary comments._

2021-03-19 03:03 UTC, sudipg4112001 commented
> @sudipg4112001 **Really Appreciate your work within time,**
> do few changes to make it more understandable
> _Add Description at starting & Add test case/output time and space complexity at Last add necessary comments._

All the changes should be made within the code or I need to make them in a separate file .. ??

2021-03-19 03:45 UTC, krishna-NIT commented
> > @sudipg4112001 **Really Appreciate your work within time,**
> > do few changes to make it more understandable
> > _Add Description at starting & Add test case/output time and space complexity at Last add necessary comments._
> 
> All the changes should be made within the code or I need to make them in a separate file .. ??

do changes within code;
at starting & at ending
you can refer to a pull request which has been merged successfully in this upstream repo.

2021-03-19 04:14 UTC, sudipg4112001 commented
Okay.. I will make the changes very soon

2021-03-19 07:54 UTC, sudipg4112001 commented
Made the required changes. Please review.

2021-03-19 09:34 UTC, krishna-NIT requested changes
The description is Good, Keep it up @sudipg4112001 bro !! 👍🏻 
 but once check the readme of this repo, few changes also needed
update last 2 points at the end
![image](https://user-images.githubusercontent.com/73196470/111759688-e06a5f80-88c3-11eb-8708-88de83d0c4c5.png)

2021-03-19 09:37 UTC, sudipg4112001 commented
Okay.. Give me some time, I will update those parts.

2021-03-19 15:16 UTC, sudipg4112001 commented
The updated the code. Please do give a review.

2021-03-19 15:55 UTC, krishna-NIT approved these changes
@plazzy99 @rudrakshi99 @nakul-19 Please Check it once, ok from my side & if Proper then Merge it @sudipg4112001 has given good efforts 👍🏻 , Good Going @sudipg4112001

2021-03-20 11:43 UTC, plazzy99 requested changes
Update readme for the same

2021-03-20 12:42 UTC, sudipg4112001 commented
> Update readme for the same

Same algorithm will have codes in different languages. So, how will I create a readme.. Could you please elaborate ?

2021-03-21 17:59 UTC, sudipg4112001 commented
Please, clarify my doubt. So that I can make the changes accordingly.

2021-03-24 12:49 UTC, sudipg4112001 commented
@plazzy99 @krishna-NIT  please clarify my doubt... It's been long you didn't respond.

2021-03-24 13:18 UTC, krishna-NIT commented
> @plazzy99 @krishna-NIT please clarify my doubt... It's been long you didn't respond.

@sudipg4112001 , I think @plazzy99 wants to say that Update and Link Que in this Readme file with language
by Adding que at end
https://github.com/Algo-Phantoms/Algo-Tree/tree/main/Stack

He might be busy in another task, wait, He will Respond 👍🏻

2021-03-29 15:07 UTC, sudipg4112001 commented
@plazzy99 sir, if you have time please clarify my doubt. It's been long there is no response.

2021-04-07 04:17 UTC, rudrakshi99 commented
> > Update readme for the same
> 
> Same algorithm will have codes in different languages. So, how will I create a readme.. Could you please elaborate ?

Update the list in the Readme of stack folder.

2021-04-07 04:19 UTC, sudipg4112001 commented
> > > Update readme for the same
> > 
> > 
> > Same algorithm will have codes in different languages. So, how will I create a readme.. Could you please elaborate ?
> 
> Update the list in the Readme of stack folder.

Not clear.. please elaborate

2021-04-07 06:50 UTC, krishna-NIT commented
> > > > Update readme for the same
> > > 
> > > 
> > > Same algorithm will have codes in different languages. So, how will I create a readme.. Could you please elaborate ?
> > 
> > 
> > Update the list in the Readme of stack folder.
> 
> Not clear.. please elaborate

@sudipg4112001 add this queue here https://github.com/Algo-Phantoms/Algo-Tree/blob/main/Stack/readme.md at bottom end

2021-04-07 09:03 UTC, sudipg4112001 commented
Made the required changes. It's showing conflicting files because of the link provided. Please do review.

2021-04-07 11:51 UTC, krishna-NIT approved these changes

2021-04-07 11:52 UTC, krishna-NIT requested changes
Put Largest_Rectangle.cpp  to Code/C++/Largest_Rectangle.cpp 
not to Stack/Largest_Rectangle.cpp

2021-04-07 12:05 UTC, sudipg4112001 commented
> Put Largest_Rectangle.cpp to Code/C++/Largest_Rectangle.cpp
> not to Stack/Largest_Rectangle.cpp

That is what I have made. Please do recheck

2021-04-07 12:25 UTC, krishna-NIT commented
> > Put Largest_Rectangle.cpp to Code/C++/Largest_Rectangle.cpp
> > not to Stack/Largest_Rectangle.cpp
> 
> That is what I have made. Please do recheck

![Capture](https://user-images.githubusercontent.com/73196470/113865980-62b2b900-97ca-11eb-9345-b9bfbf065af4.JPG)

2021-04-07 12:26 UTC, krishna-NIT commented
push files to correct folder Code/C++/

2021-04-07 13:53 UTC, sudipg4112001 commented
Please review, changes are made.

2021-04-07 17:28 UTC, krishna-NIT commented
resolve conflicts

2021-04-07 17:41 UTC, sudipg4112001 commented
Done @krishna-NIT

2021-04-07 18:05 UTC, krishna-NIT approved these changes

2021-04-09 14:58 UTC, tarun26091999 commented on Stack/readme.md
> + LR
remove this line

2021-04-09 14:59 UTC, tarun26091999 commented on Stack/readme.md
> + main
remove this also

2021-04-09 14:59 UTC, tarun26091999 commented on Stack/readme.md
> +- Largest Rectangle ----> [C++](/Code/C++/Largest_Rectangle.cpp)
make uniform indentation.

2021-04-09 15:01 UTC, tarun26091999 requested changes
put the testcases one below another, same with the complexities and also use comments to explain your steps.

2021-04-09 15:02 UTC, sudipg4112001 commented on Stack/readme.md
> + main
> remove this also

both the lines ?

2021-04-09 15:24 UTC, sudipg4112001 commented
@tarun26091999 @krishna-NIT @rudrakshi99 @plazzy99  I have made the required changes suggested. Please review.

2021-04-13 03:37 UTC, sudipg4112001 commented
Please review this PR. 4 days passed by since I have made the changes.

2021-05-24 08:14 UTC, tarun26091999 approved these changes

2021-05-24 08:17 UTC, merged