Book Allocation Problem- JAVA
Algo-Phantoms/Algo-Tree pull request #1191
Opened 2021-03-19 22:35 UTC by shahina-bano

Added code for Book Allocation in JAVA for issue #665

2021-03-26 07:58 UTC, shahina-bano commented
please review it @raksha009 @rudrakshi99

2021-03-26 18:57 UTC, raksha009 requested changes
Please edit the readme of java and not of cpp :)

2021-03-26 18:57 UTC, raksha009 commented on Code/Java/Book_Allocation.java
> +/* problem statement: Provided "n" number of books and "m" number of students. Books are arranged in increasing number of its pages. Each student is assigned to read pages in consecutive order.
```suggestion
/* Book Allocation Problem
Problem Statement: 
Provided "n" number of books and "m" number of students. Books are arranged in increasing number of its pages. Each student is assigned to read pages in consecutive order.
```

2021-03-26 18:57 UTC, raksha009 commented on Code/Java/Book_Allocation.java
> +
Remove extra lines - line 6 and 7.

2021-03-26 18:57 UTC, raksha009 commented on Code/Java/Book_Allocation.java
> +// / Name of the class hs to be "Main" only if the class is public. */
Remove this line.

2021-03-26 18:57 UTC, raksha009 commented on Code/Java/Book_Allocation.java
> +            input -
```suggestion
            Input -

```
Keep I and O capital of Input and Output

2021-03-27 10:37 UTC, shahina-bano commented
changes are done...plz review them @raksha009 @OjusWiZard

2021-03-27 13:58 UTC, raksha009 requested changes

2021-03-27 13:58 UTC, raksha009 commented on Code/Java/Book_Allocation.java
> +class bookallocation
```suggestion
class Book_Allocation {

```

2021-03-27 14:02 UTC, raksha009 approved these changes
LGTM!

2021-03-31 06:11 UTC, Kavs-123 commented
Is the issue resolved @raksha009 @aaadddiii!
If not i will like to contribute for the same ..

2021-04-02 10:53 UTC, shahina-bano commented
I have created the PR 1 week ago and got 1 approval too for the Java language, so kindly review it @shreyanspoddar

2021-04-14 10:14 UTC, shahina-bano commented
@raksha009  plz review

2021-04-14 10:24 UTC, raksha009 requested changes

2021-04-14 10:24 UTC, raksha009 commented on Algorithm/Searching_Sorting/readme.md
> +* Book Allocation Problem ----> [Java](/Code/Java/Book_ALlocation.java)
It has to be Book Allocation only.

2021-04-14 10:24 UTC, raksha009 commented on Code/Java/Book_Allocation.java
> +                    cnt++;       // incrementing the number students
Add comments above the line.
Also, add appropriate comments only.

2021-04-14 10:24 UTC, raksha009 commented on Code/Java/Book_Allocation.java
> +    public static int binary_search( int a[], int n, int m){
Indentation!

2021-04-14 10:24 UTC, raksha009 commented on Code/Java/Book_Allocation.java
> +            while(low <= high){
Indentation!

2021-04-14 10:24 UTC, raksha009 commented on Code/Java/Book_Allocation.java
> +Time complexity : O(n*log(sum)) -  n = number of books, sum = sum of the pages of all the books
where n = number of books

2021-04-14 11:11 UTC, closed without merging