added check tree in BST in c++
Algo-Phantoms/Algo-Tree pull request #1194
Opened 2021-03-20 06:19 UTC by sakshi2707

fixes #137

2021-03-20 06:38 UTC, sakshi2707 commented
@plazzy99 please review and merge it
also add gssoc and level labels

2021-03-20 19:05 UTC, rudrakshi99 commented
add a single algorithm in a PR.

2021-03-24 13:28 UTC, plazzy99 requested changes

2021-03-24 13:28 UTC, plazzy99 commented on Tree/readme.md
> +* Check Whether given Binary Tree is BST ----> [C++](/Code/C++/check_tree_is_BST.cpp)
`Check if a Binary Tree is a valid Binary Search Tree ----> [Java](/Code/Java/check_valid_BST.java)`

This is a previous merged pr take a pull and update readme

2021-03-24 13:29 UTC, plazzy99 commented on Tree/readme.md
> +* Check Whether given Binary Tree is BST ----> [C++](/Code/C++/check_tree_is_BST.cpp)
this is to be done to resolve the conflict

2021-03-24 14:03 UTC, sakshi2707 commented
@plazzy99 done!

2021-05-29 14:13 UTC, rudrakshi99 commented
resolve merge conflicts

2021-05-30 06:46 UTC, sakshi2707 commented
@rudrakshi99 I've resolved all the confilcts. 
Please merge it ASAP otherwise more conflicts will be generated

2021-05-30 06:58 UTC, merged