Count set bits of number - python
Algo-Phantoms/Algo-Tree pull request #1216
Opened 2021-03-20 20:01 UTC by shahina-bano

Added code for Count Set Bits of number for issue #44

2021-03-21 17:53 UTC, plazzy99 requested changes

2021-03-21 17:53 UTC, plazzy99 commented on Algorithm/Searching_Sorting/readme.md
> +
delete this redundant edit

2021-03-21 17:53 UTC, plazzy99 commented on Algorithm/Bit_manipulation/readme.md
> +* Count set bits of a number ----> [Python](/Code/Python/setbits.py)
Wrong name of program

2021-03-21 19:31 UTC, shahina-bano commented
I have resolved the conflict, please check it now.

2021-04-23 17:04 UTC, plazzy99 requested changes

2021-04-23 17:04 UTC, plazzy99 commented on Algorithm/Searching_Sorting/readme.md
> -
remove this edit

2021-04-23 17:05 UTC, plazzy99 commented
Resolve conflict

2021-04-24 06:09 UTC, shahina-bano commented
@plazzy99 actually I am facing some issue in this PR while editing so I am closing this PR and open a new PR for the same code. Hope it's not a problem.

2021-04-24 06:49 UTC, closed without merging

2021-04-24 06:55 UTC, plazzy99 commented
> @plazzy99 actually I am facing some issue in this PR while editing so I am closing this PR and open a new PR for the same code. Hope it's not a problem. 

Not a problem but learn to fix this. You can it learn youtube.

2021-04-24 07:03 UTC, shahina-bano commented
The problem was in branch so that's why, although I have resolved it .. thank you :)