Fibonacci Series
Algo-Phantoms/Algo-Tree pull request #1224
Opened 2021-03-21 07:10 UTC by pallavidhere23

Issue #635  (fibonacci series) solved here in java.

2021-03-23 03:09 UTC, raksha009 requested changes

2021-03-23 03:09 UTC, raksha009 commented on Algorithm/Number_theory/readme.md
> +- Fibonacci Series in Java ----> [Java](/Code/Java/Fibonacci_Series.java)
```suggestion
- Fibonacci Series ----> [Java](/Code/Java/Fibonacci_Series.java)
```

2021-03-23 03:09 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +/**
Remove lines from 4 to 10.

2021-03-23 03:09 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +
Remove extra line.

2021-03-23 03:09 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +                  int t1=0;
Add space around the operators like <, =, > etc.

2021-03-23 03:24 UTC, pallavidhere23 commented
@raksha009 I have done all the requested chances .Please review it.

2021-03-24 01:24 UTC, raksha009 requested changes
Please go through the guidelines!!

2021-03-24 01:24 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +/**
Heyy, since working in open source, we donot generally mention our names as the contributor of every code. Pl delete this comment. :)

2021-03-24 01:24 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +         and store it */
Merge it to a single comment.

2021-03-24 01:24 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +          a[0] = 0;
Use appropriate variable names!

2021-03-24 01:24 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> + * (for method 1)
```suggestion
 * (Method 1 - Via For Loop)
```
Make similar changes for mentioning other methods as well!

2021-03-24 01:24 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +/*
Include all this in single multiline comment

2021-03-24 01:24 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +Sample test cases
```suggestion
Test Cases
Input:
Output:
```
Follow this

2021-03-24 03:30 UTC, pallavidhere23 commented
@raksha009 I have done all the requested changes. Kindly review it.

2021-03-26 18:26 UTC, raksha009 requested changes

2021-03-26 18:26 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> + * Test cases
Include 2 test cases

2021-03-26 18:26 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> + * Enter the number of elements: 9
Follow the fornat of 
Input
Output

2021-03-26 18:26 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +   1
Take input in 1 line

2021-03-26 18:26 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> + * (Method 1 - Via for Loop)
1.Enter Time complexity after test cases.
2. follow the multiline  comment format as /* ... */ .-> do not add extra * in lines.

2021-03-26 18:26 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +
Remove these 2 extra lines.

2021-03-27 10:15 UTC, pallavidhere23 commented
@raksha009  I have made all requested changes. Please review it.

2021-03-27 13:56 UTC, raksha009 requested changes

2021-03-27 13:56 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +         for (i = 2; i <= n; i++)
Pl align { of for loop
or you can add like 
```suggestion
         for (i = 2; i <= n; i++) {
```

2021-03-27 13:56 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +                   {
Pl align { of for loop
or you can add like 
```suggestion
         for (i = 2; i <= n; i++) {
```

2021-03-27 13:56 UTC, raksha009 commented on Code/Java/Fibonacci_Series.java
> +  Enter the number of elements: 6
Write test cases in format:
Input 
Output

2021-03-27 15:14 UTC, pallavidhere23 commented
@raksha009  all the requested changes has been made, Please Review it.

2021-03-27 20:33 UTC, raksha009 approved these changes

2021-04-19 17:16 UTC, rudrakshi99 commented
please resolve the merge conflicts.

2021-04-20 07:15 UTC, pallavidhere23 commented
> please resolve the merge conflicts.

@rudrakshi99 , I have solve the merge conflicts.

2021-04-20 11:58 UTC, merged