N-ary (general) tree
Algo-Phantoms/Algo-Tree pull request #1234
Opened 2021-03-21 14:05 UTC by Aarti002

issue #694 solved
python

2021-03-31 15:16 UTC, Aarti002 commented
hello @sayantani11 , i think i have made required changes can you please review my code again
Thank you!

2021-04-01 15:47 UTC, sayantani11 approved these changes

2021-04-26 05:06 UTC, Rohan27s commented
@Aarti002 Update the Read me first

2021-04-26 17:53 UTC, Aarti002 commented
@Rohan27s i updated readme file but i don't know why it shows conflicts everytime i do it?

2021-04-27 06:41 UTC, Rohan27s requested changes

2021-04-27 06:41 UTC, Rohan27s commented on Code/Python/n_ary_tree.py
> +
Remove the unnecessary spaces from the whole code

2021-04-27 06:41 UTC, Rohan27s commented on Code/Python/n_ary_tree.py
> +# Firstly, class treenode is defined with several inner functions including "__init__" for creating tree node with chils as list and #intitially storing 'None' as address of parent, "add_child" add d
Use multi-line comment here and remove the space

2021-04-29 05:36 UTC, Rohan27s approved these changes

2021-04-29 05:36 UTC, merged