Check weather given string is palindrome or not
Algo-Phantoms/Algo-Tree pull request #1239
Opened 2021-03-21 14:57 UTC by Aarti002

issue #346 solved
Python
Doubly linked list

2021-03-21 15:01 UTC, ANAMIKA1410 commented
hello ;
I'm Anamika jain , GSSoC participant
please assign this to me @Aarti002 @anubhavitis @aaadddiii @tarun26091999 @dheerajkotwani

2021-03-21 15:05 UTC, ANAMIKA1410 reviewed
def isPalindrome(str):
 
    # Run loop from 0 to len/2 
    for i in range(0, int(len(str)/2)): 
        if str[i] != str[len(str)-i-1]:
            return False
    return True

2021-03-23 16:24 UTC, Aarti002 commented
hey @ANAMIKA1410 i'm a participant as well :)

2021-03-28 07:32 UTC, krishantraj commented
can I solve this issue #1239 in java without using a linked list? if yes so please assign it to me.

2021-04-16 07:33 UTC, plazzy99 requested changes
update readme

2021-04-16 07:33 UTC, plazzy99 commented on Linked_list/Python/isPalindrom_dll.py
> +    #items.print_foward()
time and space complexity required at bottom

2021-04-16 14:33 UTC, Aarti002 commented
@plazzy99 i have a doubt where we should keep this solutions file? in "Code"  folder or topic related folder like in this case "Linked-List", please help!
Thank you!

2021-04-23 17:02 UTC, plazzy99 commented
> @plazzy99 i have a doubt where we should keep this solutions file? in "Code" folder or topic related folder like in this case "Linked-List", please help!
> Thank you!

https://github.com/Algo-Phantoms/Algo-Tree/issues/1202

2021-04-24 04:23 UTC, Aarti002 commented
@plazzy99 please check once i have added my code link in readme file
Thank you!

2021-05-07 15:58 UTC, rudrakshi99 commented
Please resolve merge conflicts.

2021-05-22 07:23 UTC, tarun26091999 commented
@rudrakshi99 look into it.

2022-09-17 10:49 UTC, closed without merging