Root to leaf sum
Algo-Phantoms/Algo-Tree pull request #1242
Opened 2021-03-21 16:25 UTC by Aarti002

issue #917 solved
python

2021-04-17 17:08 UTC, plazzy99 requested changes
Update the readme

2021-04-17 17:08 UTC, plazzy99 commented on Tree/Python/root_to_leaf_sum.py
> +    root.left=new_node(12)
update the code to take dynamic input

2021-04-17 17:08 UTC, plazzy99 commented on Tree/Python/root_to_leaf_sum.py
> +#output: True
2 test cases with time and space complexity

2021-04-17 17:08 UTC, plazzy99 commented on Tree/Python/root_to_leaf_sum.py
> +#language: python
describe the question little bit

2021-04-19 05:58 UTC, Aarti002 commented
hey @plazzy99 i have added examples and  complexities please review it once.
Thank u!

2021-04-23 17:00 UTC, plazzy99 commented
> hey @plazzy99 i have added examples and complexities please review it once.
> Thank u!

update readme

2021-04-24 04:24 UTC, Aarti002 commented
please check once i have added my code link in readme file @plazzy99 

Thank you!

2021-05-01 14:29 UTC, Aarti002 commented
@plazzy99 please review my code again
Thank you!

2021-05-03 08:55 UTC, plazzy99 requested changes

2021-05-03 08:55 UTC, plazzy99 commented on Tree/readme.md
> +* Searching in BST ----> [C++](/Code/C++/searching_in_bst.cpp)
duplicate bst added please correct this

2021-05-03 18:33 UTC, Aarti002 commented
@plazzy99 i have made requested changes please check once.
Thank you!

2021-05-09 20:34 UTC, tarun26091999 commented
@Aarti002 conflict present.

2021-05-10 08:00 UTC, Aarti002 commented
sorry for conflicts you can review now @tarun26091999 
Thank you!

2021-05-30 07:09 UTC, merged