Longest Palindromic Substring Python
Algo-Phantoms/Algo-Tree pull request #1250
Opened 2021-03-22 06:11 UTC by Muskan0

#455

2021-05-08 16:56 UTC, Muskan0 commented
@tarun26091999 please merge it.

2021-05-25 15:58 UTC, rish-singhal requested changes

2021-05-25 15:58 UTC, rish-singhal commented on Code/Python/longest_palindromic_substring.py
> +    # start of the palindrome
Hey try out pep8 and solve the issues.

2021-05-25 15:58 UTC, rish-singhal commented on Code/Python/longest_palindromic_substring.py
> +Time Complexity: O(n^2)
Describe what n is here

2021-05-25 15:58 UTC, rish-singhal commented on Algorithm/DP/readme.md
>  - Climbing Stairs ----> [C++](/Code/C++/Climbing_Stairs.cpp)
Sort this whole list.

2021-05-26 07:33 UTC, Muskan0 commented
@rish-singhal Please review it.

2021-05-26 07:45 UTC, rish-singhal commented
Why have you changed the readme in DP section? It should be changed in strings

2021-05-26 07:46 UTC, rish-singhal requested changes

2021-05-26 07:46 UTC, rish-singhal commented on Algorithm/DP/readme.md
> +- Longest Palindromic Substring ----> [Python](/Code/Python/longest_palindromic_substring.py)
Sort this whole list

2021-05-26 09:35 UTC, Muskan0 commented
> Why have you changed the readme in DP section? It should be changed in strings

I used the DP approach, that's why I entered it in DP section. I changed it now.

2021-05-26 10:39 UTC, rish-singhal requested changes
You just need to sort both readme.

2021-05-26 10:39 UTC, rish-singhal commented on string/readme.md
>  * Kth Minimum in array ---->[Python](/Code/Python/Kth_Minimum_in_array.py)
Sort both the readme files,

2021-05-26 10:39 UTC, rish-singhal commented on Algorithm/DP/readme.md
>  - Word Wrap Problem ----> [C++](/Code/C++/word_wrap.cpp)
Sort this readme too

2021-05-26 13:45 UTC, rish-singhal commented on string/readme.md
>  * Kth Minimum in array ---->[Python](/Code/Python/Kth_Minimum_in_array.py)
This list is not sorted still

2021-05-26 13:46 UTC, rish-singhal requested changes

2021-05-26 13:46 UTC, rish-singhal commented on Code/Python/longest_palindromic_substring.py
> +for _ in range(int(input())):
Add empty line here

2021-05-26 14:15 UTC, rish-singhal requested changes

2021-05-26 14:15 UTC, rish-singhal commented on Algorithm/DP/readme.md
remove spaces in between

2021-05-26 14:52 UTC, merged