Added shortest common Supersequence in cpp
Algo-Phantoms/Algo-Tree pull request #1288
Opened 2021-03-23 20:07 UTC by bitaashna

I have added **'Shortest Common SuperSequence'** in **Cpp**
#167

2021-03-25 04:49 UTC, OjusWiZard requested changes
Add the Algo name to the Readme too

2021-03-25 04:49 UTC, OjusWiZard commented on Code/C++/print_shortest_supersequence.cpp
> +        Length of Shortest Common SuperSequence: 5
Align the indentation as above

2021-03-25 07:09 UTC, bitaashna commented
@OjusWiZard I have made the changes..Please review!

2021-04-01 07:14 UTC, OjusWiZard approved these changes
LGTM

2021-04-02 05:21 UTC, raksha009 commented on Code/C++/print_shortest_supersequence.cpp
> +        for (int j = 0; j <= m; j++) { //base condition
Add comments above the line

2021-04-02 05:22 UTC, raksha009 commented on Code/C++/print_shortest_supersequence.cpp
> +        for (int j = 1; j < m + 1; j++) { //cheking if character matches or not
Add comments above the line

2021-04-02 05:23 UTC, raksha009 commented on Code/C++/print_shortest_supersequence.cpp
> +  * For s1 = "a c b c f" and s2 = "a b c d a f"
Mention "Explanation" here

2021-04-02 05:24 UTC, raksha009 commented on Code/C++/print_shortest_supersequence.cpp
> +  * and LCS matrix for this is :
Remove * from the front throughout from 132 - 172.

2021-04-02 05:25 UTC, raksha009 requested changes

2021-04-02 05:25 UTC, raksha009 commented on Code/C++/print_shortest_supersequence.cpp
> +* Time Complexity: O(m*n)
Specify m and n

2021-04-02 05:25 UTC, raksha009 commented on Code/C++/print_shortest_supersequence.cpp
> +  * and LCS matrix for this is :
Remove * from the front throughout from 132 - 172.

2021-04-02 05:25 UTC, raksha009 commented on Code/C++/print_shortest_supersequence.cpp
> +  * For s1 = "a c b c f" and s2 = "a b c d a f"
Mention "Explanation" here

2021-04-02 05:32 UTC, bitaashna commented
@raksha009 I have made the changes.Please review.

2021-04-02 08:24 UTC, raksha009 requested changes

2021-04-02 08:24 UTC, raksha009 commented on Code/C++/print_shortest_supersequence.cpp
> +        for (int j = 1; j < m + 1; j++) { //cheking if character matches or not
Hey, plz add comments above the line throughout yr code.

2021-04-02 08:24 UTC, raksha009 commented on Code/C++/print_shortest_supersequence.cpp
> +        else { //push character of s1 in result
add comments above the line

2021-04-02 08:42 UTC, bitaashna commented
@raksha009 Done.Please review!

2021-04-02 09:30 UTC, raksha009 approved these changes

2021-04-02 09:31 UTC, merged