Number OF times Sorted array rotated in cpp
Algo-Phantoms/Algo-Tree pull request #1291
Opened 2021-03-23 21:10 UTC by bitaashna

I have added **'Number of times sorted array rotated'** in **Cpp**
#169

2021-03-25 04:54 UTC, OjusWiZard commented
Add the Algo name in the readme

2021-03-25 07:15 UTC, bitaashna commented
@OjusWiZard Done!

2021-04-01 07:34 UTC, OjusWiZard requested changes

2021-04-01 07:34 UTC, OjusWiZard commented on Code/C++/no_of_rotation.cpp
> +    //iterating the elements until i is less than equal to r
'l' instead of i

2021-04-01 07:34 UTC, OjusWiZard commented on Code/C++/no_of_rotation.cpp
> +  * Space Complexity: O(n)
Complexities seem incorrect to me. Please recheck.

2021-04-01 07:34 UTC, OjusWiZard commented on Algorithm/DP/readme.md
> +
There is no Dynamic Programming approach in this algorithm. So, please don't link in the DP folder.

2021-04-01 15:10 UTC, bitaashna commented
@OjusWiZard Please review,I have made the changes

2021-04-06 18:56 UTC, OjusWiZard approved these changes

2021-04-08 06:46 UTC, nakul-19 approved these changes

2021-04-08 06:46 UTC, merged