updated c++ codes (string_to_uppercase_and_lowercase)
Algo-Phantoms/Algo-Tree pull request #1302
Opened 2021-03-24 13:42 UTC by dhruvdy

2021-03-25 04:56 UTC, OjusWiZard commented
To which issue does this belong?

2021-03-25 06:15 UTC, dhruvdy commented
#656

2021-03-25 17:15 UTC, rudrakshi99 requested changes

2021-03-25 17:15 UTC, rudrakshi99 commented on Code/C++/string_to_lowercase_and_uppercase.cpp
> +   Time complexity O(n)
add complexities to the end.

2021-03-25 17:15 UTC, rudrakshi99 commented on Code/C++/string_to_lowercase_and_uppercase.cpp
> +#include<string.h>
use only `string`

2021-03-28 18:13 UTC, dhruvdy commented
Can one of the admins verify the code ?
I made the changes as requested.

2021-03-29 15:44 UTC, rudrakshi99 approved these changes

2021-03-29 15:47 UTC, rudrakshi99 commented
@dhruvdy update the list in the string folder.

2021-03-30 16:20 UTC, dhruvdy commented
@rudrakshi99 I have updated the list in string folder.

2021-04-02 18:46 UTC, rudrakshi99 commented
please resolve merge conflicts then we are good to merge.

2021-04-03 08:37 UTC, dhruvdy commented
@rudrakshi99 I am unable to make this conflicting file correct. Please help me.

2021-04-04 10:38 UTC, dhruvdy commented
@rudrakshi99 please, can you check the readme file now. Is it fine?

2021-04-04 14:13 UTC, OjusWiZard requested changes
Maintain the indentation of 4 spaces throughout the code.

2021-04-04 14:13 UTC, OjusWiZard commented on Code/C++/string_to_lowercase_and_uppercase.cpp
> +
Remove this line

2021-04-05 05:15 UTC, dhruvdy commented
@OjusWiZard I made the changes as said. Please review the code and kindly merge it if everything is fine now.

2021-04-12 18:07 UTC, rudrakshi99 commented on Code/C++/string_to_lowercase_and_uppercase.cpp
> +       if(s1[i]>=97 && s1[i]<=122)
use curly brackets for `for loop`

2021-04-12 19:07 UTC, dhruvdy commented
@rudrakshi99 I did it. Please check if some other changes are to be done..

2021-04-16 14:53 UTC, rudrakshi99 approved these changes

2021-04-16 14:54 UTC, merged