Dutch National Flag Algorithm
Algo-Phantoms/Algo-Tree pull request #1316
Opened 2021-03-25 14:17 UTC by Rajashri14

2021-03-27 14:35 UTC, raksha009 commented
Plz add issue no

2021-03-30 05:08 UTC, sayantani11 requested changes

2021-03-30 05:08 UTC, sayantani11 commented on Code/Java/Segregate01and2.java
> +        int a[] = {1, 0, 2, 1, 0, 2, 1, 0, 0, 1,0};
Try to take user input

2021-03-30 05:08 UTC, sayantani11 commented on Code/Java/Segregate01and2.java
> +
Add sample input here

2021-03-30 05:08 UTC, sayantani11 commented on Code/Java/Segregate01and2.java
> +
Remove extra spaces

2021-03-30 05:08 UTC, sayantani11 commented on Code/Java/Segregate01and2.java
> +
Add the sample output here

2021-03-30 06:13 UTC, raksha009 reviewed
Plz link your code to required file, Go through the guidelines and pinned issues.

2021-04-11 03:20 UTC, raksha009 requested changes
Hey, plz go through the guidelines and the pinned issues and link the code with required folder.

2021-04-11 03:20 UTC, raksha009 commented on Code/Java/Segregate01and2.java
> +*/
Add a new line here.

2021-04-13 09:29 UTC, raksha009 commented
Are you still working on it ?

2021-05-11 14:42 UTC, raksha009 commented
> Plz add issue no

plz specify

2021-05-11 14:45 UTC, raksha009 requested changes

2021-05-11 14:45 UTC, raksha009 commented on Code/Java/Segregate01and2.java
> +// Sample Output - 0 0 0 0 0 1 1 1 1 2 2
Follow 
Test Cases
Input : 
Ouput :

Add atleast 2 test cases 
Add add the test cases and complexities in a single multiline comment.

2021-05-11 14:45 UTC, raksha009 commented on Code/Java/Segregate01and2.java
> +// Sample Input - 1 0 2 1 0 2 1 0 0 1 0
Remove this line

2021-05-13 17:08 UTC, raksha009 commented
Issue #958

2021-05-13 17:09 UTC, raksha009 requested changes
Update special algo readme and not the java one readme. 
Just make these changes, will merge after this 👍🏼

2021-05-13 17:09 UTC, raksha009 commented on Code/Java/Segregate01and2.java
> +Time Complexity   -  O(n)
Specify n

2021-05-17 17:52 UTC, merged