Reversing a string in java
Algo-Phantoms/Algo-Tree pull request #132
Opened 2021-03-04 05:18 UTC by prateek-jpg

Reversing a string using stacks.Please consider this under GSSOC'21.
Fixes #98

2021-03-11 13:14 UTC, raksha009 requested changes
Plz remove the extra file

2021-03-11 15:08 UTC, prateek-jpg commented
@raksha009  Extra files removed.

2021-03-11 15:17 UTC, rudrakshi99 requested changes

2021-03-11 15:17 UTC, rudrakshi99 commented on Stack/Reverse_String.java
> +	String s=sc.nextLine();												//Enter the string you want to reverse
Do not add too many spaces at the starting of comments. Add the comments just above the code.

2021-03-11 15:17 UTC, rudrakshi99 commented on Stack/Reverse_String.java
> +        int l=s.length();												//Storing the length of the string
Do not add too many spaces at the starting of comments. Add the comments just above the code.

2021-03-11 15:17 UTC, rudrakshi99 commented on Stack/Reverse_String.java
> +            a.push(ch);													//adding each character to the stack
Do not add too many spaces at the starting of comments. Add the comments just above the code.

2021-03-11 15:17 UTC, rudrakshi99 commented on Stack/Reverse_String.java
> +            s=s+a.pop();												//as pop occurs from top therefore while popping a character we add it to a string which is stored in reverse order
Do not add too many spaces at the starting of comments. Add the comments just above the code.

2021-03-11 15:17 UTC, rudrakshi99 commented on Stack/Reverse_String.java
> +        Stack<Character> a=new Stack<>();             									//Creating a stack named "a"
Do not add too many spaces at the starting of comments. Add the comments just above the code.

2021-03-11 15:19 UTC, rudrakshi99 commented on Stack/Reverse_String.java
> +	Time Complexity-O(n)
use `:` instead of `-`.

2021-03-11 15:19 UTC, rudrakshi99 commented on Stack/Reverse_String.java
> +	Space Complexity-O(n)
use `:` instead of  `-`.

2021-03-11 17:19 UTC, prateek-jpg commented
@rudrakshi99 I have removed extra spaces which were unnecessary and made the changes mentioned. Kindly check it and let me know if any other change is required.

2021-03-11 18:24 UTC, raksha009 requested changes
Link it to the folder.

2021-03-11 18:24 UTC, raksha009 commented on Stack/Reverse_String.java
> +
Remove extra space

2021-03-11 18:24 UTC, raksha009 commented on Stack/Reverse_String.java
> +
Remove extra space

2021-03-12 05:34 UTC, prateek-jpg commented
@raksha009  Removed extra spaces and also linked the file in readme.

2021-03-12 05:53 UTC, raksha009 approved these changes

2021-03-13 11:39 UTC, prateek-jpg commented
Hiii @rudrakshi99 
Please let me know if there are any other changes required in my PR.

2021-03-14 05:44 UTC, Manish5237 commented
Hi ,

I am GSSOC'21 participant.
Please assign me this. I will do this in C with proper comments and test cases.

@rudrakshi99

2021-03-14 08:44 UTC, tarun26091999 requested changes
this should be linked to string folder, not stack

2021-03-14 09:12 UTC, prateek-jpg commented
@tarun26091999  have linked to string folder.

2021-03-20 06:15 UTC, naqeeb2710 commented
can i work on this issue?

2021-04-13 19:54 UTC, tarun26091999 requested changes
where is your code?

2021-04-16 15:13 UTC, rudrakshi99 commented
Please resolve merge conflicts.

2021-04-19 04:32 UTC, closed without merging