Right side view of binary in java
Algo-Phantoms/Algo-Tree pull request #1347
Opened 2021-03-28 06:49 UTC by krishnmohan19

2021-03-28 21:12 UTC, raksha009 requested changes

2021-03-28 21:12 UTC, raksha009 commented on Code/Java/Right_Side_View_Of_BinaryTree.java
> +class Main
```suggestion
class Right_Side_View_Of_BinaryTree
```

2021-03-28 21:12 UTC, raksha009 commented on Code/Java/Right_Side_View_Of_BinaryTree.java
> +        Node root = new Node(1);
Plz take input dynamically!

2021-04-02 18:29 UTC, krishnmohan19 commented
hey @raksha009 ,
i have made changes .plz review it.

2021-04-06 13:04 UTC, raksha009 requested changes
Just make this small change, rest LGTM

2021-04-06 13:04 UTC, raksha009 commented on Tree/readme.md
> +* Right Side View of Binary Tree ----> [JAVA](/Code/java/Right_Side_View_Of_BinaryTree.java)
```suggestion
* Right Side View of Binary Tree ----> [Java](/Code/java/Right_Side_View_Of_BinaryTree.java)
```

2021-04-06 13:05 UTC, raksha009 commented
Also, resolve the conflicts :)

2021-05-16 19:34 UTC, tarun26091999 commented
#1061

2021-05-16 19:34 UTC, merged