Generate all valid parentheses - Java
Algo-Phantoms/Algo-Tree pull request #1394
Opened 2021-03-30 19:45 UTC by shahina-bano

Added the code for issue #732 in Java.

2021-04-06 13:10 UTC, raksha009 requested changes

2021-04-06 13:10 UTC, raksha009 commented on Code/Java/valid_parantheses.java
> +/*Generate all valid parantheses
```suggestion
/*
Generate all valid parentheses

```

2021-04-06 13:10 UTC, raksha009 commented on Code/Java/valid_parantheses.java
> +Problem  Statement: Write a program to generate all possible "n" pairs of balanced parantheses.
Describe in a bit more detail.

2021-04-06 13:10 UTC, raksha009 commented on Code/Java/valid_parantheses.java
> +                    System.out.print(str[i]);           //printing all pairs of parantheses
Add comments above the line throughout the code.

2021-04-06 13:10 UTC, raksha009 commented on Code/Java/valid_parantheses.java
> +                int n = 0;
Remove this comment

2021-04-06 13:10 UTC, raksha009 commented on Code/Java/valid_parantheses.java
> +        		valid_paranthesis(arr, n);                      //calling the function
Remove this comment

2021-04-06 13:10 UTC, raksha009 commented on Code/Java/valid_parantheses.java
> +/*Test Case 1:
```suggestion
/*
Test Cases: 

```
Follow this format
Test Case
1. 
Input : 
Output :

2021-04-06 13:10 UTC, raksha009 commented on Code/Java/valid_parantheses.java
> +Space Complexity: O(n)
Specify n

2021-04-06 14:14 UTC, shahina-bano commented
Done @raksha009 :))

2021-04-12 17:49 UTC, raksha009 requested changes

2021-04-12 17:49 UTC, raksha009 commented on Code/Java/valid_parantheses.java
> +        		valid_paranthesis(arr, n);
Indentation!

2021-04-12 17:49 UTC, raksha009 commented on Code/Java/valid_parantheses.java
> +                     //calling the function for the next position using recursion
Remove this comment.

2021-04-12 17:49 UTC, raksha009 commented on Code/Java/valid_parantheses.java
> +                    //calling the function for the next position using recursion
Remove this comment

2021-04-14 10:06 UTC, raksha009 approved these changes
LGTM

2021-04-14 10:07 UTC, merged