Sudoku solver
Algo-Phantoms/Algo-Tree pull request #1417
Opened 2021-04-01 14:19 UTC by yashmita

Added code for Sudoku Solver in Java

2021-04-01 17:16 UTC, raksha009 requested changes

2021-04-01 17:16 UTC, raksha009 commented on Code/Java/Sudoku_Solver.java
> +	public static boolean CanPlace(int[][] mat, int n, int i, int j, int num)
Plz add comments above each func, denoting what it does.

2021-04-01 17:16 UTC, raksha009 commented on Code/Java/Sudoku_Solver.java
> +SPACE COMPLEXITY: O(n*n)
Specify n

2021-04-01 20:06 UTC, yashmita commented
Okay, I've updated the changes as suggested. Kindly have a look.

2021-04-02 03:13 UTC, raksha009 approved these changes
LGTM 👍🏼

2021-04-02 09:10 UTC, merged