added sorted & unsorted ziz-zag array and modified related readme.md
Algo-Phantoms/Algo-Tree pull request #1423
Opened 2021-04-02 10:38 UTC by imsushant12

I have added the sorted and unsorted zig-zag array in cpp and updated corresponding readme.md file

ASSIGNED ISSUE : Adding Zig Zag Array #234
link : https://github.com/Algo-Phantoms/Algo-Tree/issues/234

2021-04-27 13:24 UTC, plazzy99 commented
Resolve conflicts

2021-05-01 09:33 UTC, imsushant12 commented
@raksha009 and @OjusWiZard please review.

2021-05-19 12:18 UTC, rish-singhal requested changes

2021-05-19 12:18 UTC, rish-singhal commented on Code/C++/sorted_zig_zag_array.cpp
> +#include <bits/stdc++.h>
add description at the top

2021-05-19 12:18 UTC, rish-singhal commented on Code/C++/sorted_zig_zag_array.cpp
> +    cout<<"Original array  : ";
add spaces around operators everywhere "<<, ==, ...."

2021-05-19 12:18 UTC, rish-singhal commented on Code/C++/unsorted_zig_zag_array.cpp
> +
atleast add 2 test_cases

2021-05-19 12:18 UTC, rish-singhal commented on Code/C++/unsorted_zig_zag_array.cpp
> +#include <bits/stdc++.h>
same changes required as above.

2021-05-19 13:39 UTC, imsushant12 commented on Code/C++/sorted_zig_zag_array.cpp
> +#include <bits/stdc++.h>
done sir, please review

2021-05-19 13:39 UTC, imsushant12 commented on Code/C++/unsorted_zig_zag_array.cpp
> +
done sir, please review

2021-05-19 13:39 UTC, imsushant12 commented on Code/C++/sorted_zig_zag_array.cpp
> +    cout<<"Original array  : ";
done sir, please review

2021-05-19 13:39 UTC, imsushant12 commented on Code/C++/unsorted_zig_zag_array.cpp
> +#include <bits/stdc++.h>
done sir, please review

2021-05-28 18:00 UTC, rish-singhal requested changes
only 3 minor changes!

2021-05-28 18:00 UTC, rish-singhal commented on Array/readme.md
> +- Find duplicate in array ----> [C++](/Code/C++/Duplicate_in_array.cpp)
sort this list.

2021-05-28 18:00 UTC, rish-singhal commented on Code/C++/sorted_zig_zag_array.cpp
> +    Time Complexity : O(n log n)
describe what n is

2021-05-28 18:00 UTC, rish-singhal commented on Code/C++/unsorted_zig_zag_array.cpp
> +    Time Complexity : O(n)
describe what n is

2021-05-28 18:00 UTC, rish-singhal commented
Resolve conflicts too!

2021-05-28 18:37 UTC, imsushant12 commented on Code/C++/unsorted_zig_zag_array.cpp
> +    Time Complexity : O(n)
done sir.

2021-05-28 18:37 UTC, imsushant12 commented on Code/C++/sorted_zig_zag_array.cpp
> +    Time Complexity : O(n log n)
done sir

2021-05-28 18:38 UTC, imsushant12 commented on Array/readme.md
> +- Find duplicate in array ----> [C++](/Code/C++/Duplicate_in_array.cpp)
done sir

2021-05-28 18:49 UTC, merged