Tower of Hanoi in Python
Algo-Phantoms/Algo-Tree pull request #1431
Opened 2021-04-02 15:27 UTC by sayantani11

Fixes issue #828 
Review and suggest if any changes required.

2021-04-02 15:31 UTC, sayantani11 commented
@raksha009 Please review

2021-04-21 09:10 UTC, sayantani11 commented
@plazzy99 @raksha009 please review

2021-04-21 09:56 UTC, raksha009 requested changes

2021-04-21 09:56 UTC, raksha009 commented on Code/Python/Tower_of_Hanoi.py
> +   ''' This function takes the number of disks and the names of the rods.
Add this comment in brief in form of a single line comment above the function.

2021-04-21 09:56 UTC, raksha009 commented on Code/Python/Tower_of_Hanoi.py
> +''' Sample Input = 3
Plz go through guidelines and pinned issues.
Follow
Test Cases
Input : 
Output: 
(Atleast 2)

Time and space Complexities.

2021-04-21 16:04 UTC, sayantani11 commented
@raksha009 please check

2021-04-22 06:17 UTC, raksha009 requested changes

2021-04-22 06:17 UTC, raksha009 commented on Code/Python/Tower_of_Hanoi.py
> +    if(n==0): # defining the base case of the function
Add comments above the line

2021-04-22 06:17 UTC, raksha009 commented on Code/Python/Tower_of_Hanoi.py
> +    Tower_of_Hanoi(n-1,src,help,dest) # recursively calling the function
remove this comment

2021-04-22 06:17 UTC, raksha009 commented on Code/Python/Tower_of_Hanoi.py
> +    Tower_of_Hanoi(n-1,help,dest,src) #moving disk from helper to destination rod
Add comments above the line

2021-04-22 06:17 UTC, raksha009 commented on Code/Python/Tower_of_Hanoi.py
> +    n=int(input("Enter number of rods: "))  # taking the number of rods from the user
remove this comment

2021-04-22 06:17 UTC, raksha009 commented on Code/Python/Tower_of_Hanoi.py
> +    # A B C are the name of rods
Add comments above the line 40

2021-04-22 06:17 UTC, raksha009 commented on Code/Python/Tower_of_Hanoi.py
> +Sample Input :
```suggestion
Input :
```

2021-04-22 06:17 UTC, raksha009 commented on Code/Python/Tower_of_Hanoi.py
> +Sample Output:
```suggestion
Output:
```

And do this change in other i/p - o/p

2021-04-22 06:17 UTC, raksha009 commented on Code/Python/Tower_of_Hanoi.py
> +   Space Complexity : O(n)
specify n below line 69.

2021-04-22 07:07 UTC, sayantani11 commented
@raksha009

2021-04-24 13:15 UTC, raksha009 approved these changes

2021-04-24 13:15 UTC, merged