Cycle sort in cpp
Algo-Phantoms/Algo-Tree pull request #1440
Opened 2021-04-03 04:42 UTC by Harikrishnan6336

Fixes #587

2021-04-09 10:38 UTC, OjusWiZard requested changes

2021-04-09 10:38 UTC, OjusWiZard commented on Code/C++/cycle_sort.cpp
> +idea that one of the permutation of the numbers is in sorted order */
Also, write the intuition behind the working of this algorithm.

2021-04-09 10:38 UTC, OjusWiZard commented on Code/C++/cycle_sort.cpp
> +Space Complexity - O(n)
Space complexity seems incorrect to me

2021-04-09 10:38 UTC, OjusWiZard commented on Code/C++/cycle_sort.cpp
> +                pos++;
Write the purpose of this loop as a comment.

2021-04-09 10:38 UTC, OjusWiZard commented on Code/C++/cycle_sort.cpp
> +            pos += 1;
Write the purpose of this loop as a comment.

2021-04-09 10:38 UTC, OjusWiZard commented on Code/C++/cycle_sort.cpp
> +The sorted elements are :  1 2 3 4 5
Write at least **two** test cases.

2021-04-09 10:39 UTC, OjusWiZard commented
Resolve the conflict.

2021-04-17 15:55 UTC, OjusWiZard approved these changes

2021-04-17 15:56 UTC, OjusWiZard commented
Resolve the conflict again pls

2021-04-17 16:08 UTC, Harikrishnan6336 commented
@OjusWiZard Done

2021-04-17 17:10 UTC, merged