Added Issue-714 Split Array Largest Sum program in CPP
Algo-Phantoms/Algo-Tree pull request #1446
Opened 2021-04-03 11:02 UTC by Atul-Kashyap

Hey @rudrakshi99 , I added the Split Array Largest Sum c++ code in the "/Algo-Tree/C++" folder. I write code as per the guidelines.
Code passed all the test cases and if you find something wrong, please let me know.
Please merge it as soon as you can.
Thank You

issue link - #714

2021-04-11 14:29 UTC, krishna-NIT requested changes
Add this Que or Algo name at the end of    /Array/readme.md file

2021-05-30 12:52 UTC, Atul-Kashyap commented
Hi @krishna-NIT,
Can you please merge this code.

2021-05-30 13:39 UTC, krishna-NIT commented
resolve conflict

2021-05-30 13:40 UTC, krishna-NIT commented on Code/C++/split_array_largest_sum.cpp
> +
explain in brief

2021-05-30 17:17 UTC, closed without merging

2021-05-30 17:18 UTC, krishna-NIT commented
@Atul-Kashyap Why?

2021-05-30 17:41 UTC, Atul-Kashyap commented
Hi @krishna-NIT ,
I create new branch and add the program,
Can you Please merge it ?
thank you