Reverse a string
Algo-Phantoms/Algo-Tree pull request #1458
Opened 2021-04-03 20:10 UTC by yashmita

I have added the code for reversing a string using CPP for issue #611 . 
Kindly review it.

2021-04-04 04:24 UTC, raksha009 requested changes

2021-04-04 04:24 UTC, raksha009 commented on Code/C++/reverse_string.cpp
> +Given a string, print its reverse.
Plz explain a bit more by taking an example and then describing the workflow.

2021-04-04 04:24 UTC, raksha009 commented on Code/C++/reverse_string.cpp
> +	reverse(str.begin(), str.end());	//In-built function to reverse a string
Write the code without include stl,  you may tell about this stl in the description or the comments in between the code.

2021-04-04 04:24 UTC, raksha009 commented on Code/C++/reverse_string.cpp
> +//Driver function
Remove this comment.

2021-04-04 04:24 UTC, raksha009 commented on Code/C++/reverse_string.cpp
> +	getline(cin, str);	//Taking input using getline() to include whitespaces
Add comments above the line

2021-04-04 04:24 UTC, raksha009 commented on string/readme.md
> +* Reverse a strung ---->[C++](/Code/C++/reverse_string.cpp)
```suggestion
* Reverse a string ---->[C++](/Code/C++/reverse_string.cpp)
```

2021-04-04 16:07 UTC, raksha009 requested changes

2021-04-04 16:07 UTC, raksha009 commented on string/readme.md
> +* Reverse a strung ---->[C++](/Code/C++/reverse_string.cpp)
```suggestion
* Reverse a string ---->[C++](/Code/C++/reverse_string.cpp)
```

2021-04-05 03:45 UTC, raksha009 approved these changes
LGTM 👍🏼

2021-04-05 16:10 UTC, einhawking commented
I am a participant GSSOC'21
I would like to contribute in this

2021-04-09 10:55 UTC, OjusWiZard requested changes

2021-04-09 10:55 UTC, OjusWiZard commented on Code/C++/reverse_string.cpp
> +We can also reverse a string using a predefined function in CPP i.e., reverse()
...predefined function in **STL of** CPP i.e., **std::** reverse()

2021-04-09 10:55 UTC, OjusWiZard commented on Code/C++/reverse_string.cpp
> +	}
Try adding the core algorithm in a separate function.

2021-04-09 20:58 UTC, yashmita commented
@OjusWiZard I have updated the changes as suggested. Kindly have a look.

2021-04-13 15:31 UTC, OjusWiZard approved these changes

2021-04-13 15:38 UTC, merged