Find Duplicate in Array in CPP
Algo-Phantoms/Algo-Tree pull request #1469
Opened 2021-04-04 14:42 UTC by shahina-bano

I have added the code for issue #777 . Kindly review it @tarun26091999 @rudrakshi99

2021-04-04 16:27 UTC, sayantani11 requested changes

2021-04-04 16:27 UTC, sayantani11 commented on Code/C++/repeated_element.cpp
> +{
Where is the input statement?

2021-04-04 16:27 UTC, sayantani11 commented on Code/C++/repeated_element.cpp
> +{
Shouldn't be after int main()

2021-04-04 17:36 UTC, shahina-bano commented
@sayantani11 input is in the function
and what shouldn't be after int main? can you please clarify more.

2021-04-05 15:33 UTC, sayantani11 commented
I know but the conventional way somewhere makes it better for a layman

2021-04-05 17:22 UTC, shahina-bano commented
> I know but the conventional way somewhere makes it better for a layman

I think that the way in which I have written the code is quite understandable even for a layman too. If a mentor would ask me to make this change, then I'll do it :)

2021-04-08 18:29 UTC, sayantani11 approved these changes

2021-04-08 18:33 UTC, sayantani11 commented
Open source is a community where we try to help each other to get better with contributions.....I did suggest changes to few of my participant mates and they took it sportingly and it's similar with me
Anyways your files are **FAULTY** , check before pushing.... It conflicts with main branch

2021-04-08 18:34 UTC, sayantani11 commented
Thank you

2021-04-08 19:52 UTC, shahina-bano commented
> Open source is a community where we try to help each other to get better with contributions.....I did suggest changes to few of my participant mates and they took it sportingly and it's similar with me
> Anyway your files are **FAULTY** , check before pushing.... It conflicts with main branch

thank you for your suggestion, I am not opposing it though :). I'll consider this next time onwards :) @sayantani11

2021-04-15 13:18 UTC, raksha009 requested changes

2021-04-15 13:18 UTC, raksha009 commented on Code/C++/repeated_element.cpp
> +Time Complexity: O(size), for traversing the elements
Specify size

2021-04-15 13:18 UTC, raksha009 commented on Code/C++/repeated_element.cpp
> +output -
```suggestion
Output :

```

2021-04-15 13:18 UTC, raksha009 commented on Code/C++/repeated_element.cpp
> +Test Case 1:
Follow 
Test Cases
Input : 
Output :

2021-04-15 13:18 UTC, raksha009 commented on Code/C++/repeated_element.cpp
> +    cin >> size; //taking the size as input from user
Add comments above the line throughout yr code.

2021-04-19 09:03 UTC, raksha009 requested changes

2021-04-19 09:03 UTC, raksha009 commented on Array/readme.md
> + * Find duplicate in array ----> [C++](/Code/C++/repeated_element.cpp)
Plz have a suitable file name related to problem statement.

2021-04-19 09:03 UTC, raksha009 commented on Code/C++/repeated_element.cpp
> +Problem Statement: Given an array with size "size", the elements inside the array can be any number of times.
```suggestion
Problem Statement: Given an array with size "size", the elements inside the array can be present any number of times.

```

2021-04-19 09:03 UTC, raksha009 commented on Code/C++/repeated_element.cpp
> +output :
```suggestion
Output :

```

2021-04-19 09:03 UTC, raksha009 commented on Code/C++/repeated_element.cpp
> +output :
O capital

2021-04-20 11:56 UTC, raksha009 approved these changes

2021-04-20 11:57 UTC, merged