Linear Search added and readme updated
Algo-Phantoms/Algo-Tree pull request #1470
Opened 2021-04-04 15:15 UTC by vedant-jain03

issue #602 

--> Added Linear Search.cpp
--> Updated Readme.md

@raksha009 @tarun26091999 
Please review

2021-04-07 05:53 UTC, tarun26091999 requested changes
resolve the conflict and check space complexity

2021-04-07 05:58 UTC, vedant-jain03 reviewed
Space Complexity O(n) -> O(1)

2021-04-07 07:44 UTC, vedant-jain03 reviewed
Unchanged Readme.md file

2021-04-07 08:46 UTC, tarun26091999 requested changes
link it to the folder

2021-04-07 08:56 UTC, vedant-jain03 commented
> link it to the folder

@tarun26091999 
Sir actually I am not able to understand that I already have add my .cpp code in Code folder
So what else we have to link to the folder that you have requested
I am bit confuse about this part

2021-04-07 09:14 UTC, tarun26091999 commented
read the guidelines or you can see the merged PRs.

2021-04-07 10:33 UTC, vedant-jain03 reviewed
Updated Linked list.cpp and linked it to folder in Readme.md file

2021-04-18 14:30 UTC, tarun26091999 requested changes

2021-04-18 14:30 UTC, tarun26091999 commented on Code/C++/Linear_search.cpp
> +    for(int i=0;i<n;i++)
multiple declaration of i

2021-04-18 14:31 UTC, tarun26091999 commented on Algorithm/Searching_Sorting/readme.md
> +* Linear Search ----> [C++](/Code/C++/Linear_search.cpp)
remove this line and link the code to unordered linear search.

2021-04-18 14:50 UTC, vedant-jain03 reviewed
Updated

2021-04-18 15:32 UTC, tarun26091999 approved these changes

2021-04-18 15:32 UTC, merged

2021-04-18 15:43 UTC, vedant-jain03 commented
@tarun26091999 Please I guess you forgot to label and also thankyou for approving