Reverse a string in Java
Algo-Phantoms/Algo-Tree pull request #1478
Opened 2021-04-04 20:04 UTC by shahina-bano

I have added the solution for the issue #611 . Kindly review it @raksha009 @shreyanspoddar

2021-04-05 04:41 UTC, raksha009 requested changes

2021-04-05 04:41 UTC, raksha009 commented on Code/Java/reverse_string.java
> +/*Reverse string
```suggestion
/*Reverse a string using 2 pointer Approach

```

2021-04-05 04:41 UTC, raksha009 commented on Code/Java/reverse_string.java
> +        String input = sc.nextLine();       //taking input string from user
```suggestion
        String input = sc.nextLine();       

```
Remove this comment

2021-04-05 04:41 UTC, raksha009 commented on Code/Java/reverse_string.java
> +        int k = input.length();                      //size of the string
Add comments above the line

2021-04-05 04:41 UTC, raksha009 commented on Code/Java/reverse_string.java
> +        /*using two pointer type approach to swap the characters of string
Use single line comments in between the code

2021-04-05 04:41 UTC, raksha009 commented on Code/Java/reverse_string.java
> +*/
Add a new line here

2021-04-05 16:52 UTC, raksha009 requested changes

2021-04-05 16:52 UTC, raksha009 commented on Code/Java/reverse_string.java
> +                    For e.g initial string: Hello, reversed string: olleH
Add description in a bit more detail.

2021-04-05 16:52 UTC, raksha009 commented on Code/Java/reverse_string.java
> +	//input the string from user
Remove this line

2021-04-05 16:52 UTC, raksha009 commented on Code/Java/reverse_string.java
> +        char[] output = input.toCharArray();         //converting it into array to access each Character of string
Add comments above the line throughout the code,

2021-04-05 16:52 UTC, raksha009 commented on Code/Java/reverse_string.java
> +Time Complexity: O(k), for traversing the array of characters
```suggestion
Time Complexity: O(k), for traversing the array of characters

```
Specify what is k here

2021-04-06 13:21 UTC, raksha009 requested changes

2021-04-06 13:21 UTC, raksha009 commented on Code/Java/reverse_string.java
> +	//input the string from user
Remove this comment on line 17 :)

2021-04-06 13:21 UTC, raksha009 commented on Code/Java/reverse_string.java
> +        //using two pointer type approach to swap the characters of string
Add a new line before line 23

2021-04-06 13:21 UTC, raksha009 commented on Code/Java/reverse_string.java
> +        System.out.print("Reversed string: ");
Add a new line before line 31

2021-04-06 13:21 UTC, raksha009 commented on Code/Java/reverse_string.java
> +        // printing the reversed string
Remove this comment

2021-04-06 13:21 UTC, raksha009 commented on Code/Java/reverse_string.java
> +/*Reverse a string using 2 pointer Approach
```suggestion
/*
Reverse a string using 2 pointer Approach

```

2021-04-06 13:59 UTC, shahina-bano commented
Done :) @raksha009 let me know if anything else you want me to change :)

2021-04-14 10:29 UTC, raksha009 requested changes

2021-04-14 10:29 UTC, raksha009 commented on Code/Java/reverse_string.java
> +class StringReverse{
class name should be same as file name

2021-04-14 10:29 UTC, raksha009 commented on Code/Java/reverse_string.java
> +class StringReverse{
And add a new line here

2021-04-14 10:29 UTC, raksha009 commented on Code/Java/reverse_string.java
> +	//size of the string
Remove this comment.

2021-04-14 10:29 UTC, raksha009 commented on Code/Java/reverse_string.java
> +	    //swapping the characters
Remove this comment.

2021-04-14 10:29 UTC, raksha009 commented on Code/Java/reverse_string.java
> +Test Case 1:
Follow
Test Cases
Input
Output

2021-04-14 11:18 UTC, shahina-bano commented
done with the changes @raksha009

2021-04-14 14:01 UTC, raksha009 requested changes

2021-04-14 14:01 UTC, raksha009 commented on Code/Java/reverse_string.java
> +	//converting it into array to access each Character of string
Indentation

2021-04-14 14:01 UTC, raksha009 commented on string/readme.md
>  * Reverse a string ---->[C++](/Code/C++/reverse_string.cpp)
Edit 17th line 
```suggestion
* Reverse a string ---->[C++](/Code/C++/reverse_string.cpp) | [Java](/Code/Java/reverse_string.java)
```

2021-04-14 14:02 UTC, raksha009 requested changes

2021-04-14 14:02 UTC, raksha009 commented on Code/Java/reverse_string.java
> +	//calling for the reverse function from main
plz correct Indentation here too

2021-04-15 13:00 UTC, raksha009 approved these changes
LGTM 👍🏼

2021-04-15 13:01 UTC, merged