Inverse of an array
Algo-Phantoms/Algo-Tree pull request #1486
Opened 2021-04-05 08:25 UTC by Op-panda

#847

2021-04-10 09:00 UTC, krishna-NIT requested changes
Resolve Conflict

2021-04-13 09:01 UTC, Op-panda commented
should i delete that ??

2021-04-16 13:39 UTC, Op-panda commented
@raksha009 @nakul-19
@tarun26091999 @rudrakshi99 @plazzy99 @nakul-19

2021-04-16 16:29 UTC, raksha009 requested changes

2021-04-16 16:29 UTC, raksha009 commented on Code/C++/inverse_of_an_array.cpp
> +Sample input:
Hey, plz do not add sample test cases and complexity here.  Only provide a brief description of problem statement here.

2021-04-16 16:29 UTC, raksha009 commented on Code/C++/inverse_of_an_array.cpp
> +// ALGORITHM -->
Add algorithm in problem description part

2021-04-16 16:29 UTC, raksha009 commented on Code/C++/inverse_of_an_array.cpp
> +
Add in 1 line above this function about its role.

2021-04-16 16:29 UTC, raksha009 commented on Code/C++/inverse_of_an_array.cpp
> +    // Driver code begins
Remove this comment.

2021-04-16 16:29 UTC, raksha009 commented on Code/C++/inverse_of_an_array.cpp
> +    int t, n;
cout what is n, t etc. Take appropriate variable names.

2021-04-16 16:29 UTC, raksha009 commented on Code/C++/inverse_of_an_array.cpp
> +
Add testcases and complexities here. Plz follow guidelines,

2021-04-17 05:47 UTC, Op-panda commented
all changes done I hope

2021-04-18 20:13 UTC, merged