Added Perfect_number(python) issue753
Algo-Phantoms/Algo-Tree pull request #1492
Opened 2021-04-05 10:35 UTC by samya02

issue #753 
I have added the code in Code/Python perfect_number.
Please review it @OjusWiZard !
Thanks!!

2021-04-05 12:02 UTC, samya02 commented
Hi,
 I have added both the codes i.e python and cpp in their respective folders. Please review them @OjusWiZard !
Thanks a lot!!

2021-04-29 13:49 UTC, raksha009 requested changes
Plz remove .exe, .o, .py files as this pr is about yr c++ code. Also, link yr file with appropriate folder.

2021-05-02 20:42 UTC, samya02 commented
@raksha009 Made the required changes.. Kindly review!
Thanks a lot!!

2021-06-01 11:56 UTC, nakul-19 approved these changes

2021-06-01 11:57 UTC, merged