added grundy_number.cpp
Algo-Phantoms/Algo-Tree pull request #1546
Opened 2021-04-07 18:25 UTC by Shalvi-Singhal

#692 fixed.
@tarun26091999 @OjusWiZard  please review it.

2021-04-26 20:11 UTC, tarun26091999 requested changes
resolve conflicts.

2021-04-26 20:11 UTC, tarun26091999 commented on Code/C++/grundy_number.cpp
> +
remove these lines

2021-04-27 12:58 UTC, Shalvi-Singhal commented
I think , I made some mistake while committing the change, @tarun26091999  can you please help me with resolving the conflict.
I have absolutely no idea on how to fix this.

2021-04-28 17:42 UTC, Shalvi-Singhal commented
conflict resolved.

2021-04-28 18:30 UTC, Shalvi-Singhal commented
commit https://github.com/Algo-Phantoms/Algo-Tree/pull/1546/commits/84dc7d79ebbbeb5ebfd2bd6a3242da67e99ee975 was done by mistake. how can I delete it?

2021-04-30 17:55 UTC, krishna-NIT commented
> commit [84dc7d7](https://github.com/Algo-Phantoms/Algo-Tree/commit/84dc7d79ebbbeb5ebfd2bd6a3242da67e99ee975) was done by mistake. how can I delete it?

you git bash or github desktop  and then Resolve Issue of Readme, Arrange Question of Readme in alphabetical order

2021-05-31 15:40 UTC, closed without merging