Fixed Issue
Algo-Phantoms/Algo-Tree pull request #1548
Opened 2021-04-07 20:10 UTC by rk05-lenavo

#1247 ISSUE

2021-04-07 20:12 UTC, rk05-lenavo commented
@raksha009 Mam can You Please review this code. If it seems Okay to you Kindly merge my PR.

2021-04-09 15:18 UTC, tarun26091999 requested changes
take input from the user. add 2 testcases and time and space complexities.

2021-04-11 08:15 UTC, rk05-lenavo commented
@tarun26091999 Sir Please take a look.

2021-04-15 14:46 UTC, tarun26091999 requested changes
check your code again and link it to the folder.

2021-04-16 18:48 UTC, rk05-lenavo commented
@tarun26091999 Sir what's wrong in the code and how to link it in the folder I think I have done that.

2021-04-30 17:46 UTC, krishna-NIT commented on Code/C++/Intersection_point_of_linked_list.cpp
> +// Time Complexity: O(m+n)
add what is m and n here

2021-04-30 17:51 UTC, krishna-NIT commented
Update the Readme which is present at the location (Algo-Tree/Linked_list/readme.md), add this question this at Last of this Readme and arrange these question in alphabetical Order

2021-04-30 19:45 UTC, rk05-lenavo commented
@krishna-NIT Sir I have also modified the Linked_Lists/readme.md file https://github.com/Algo-Phantoms/Algo-Tree/pull/1832#issue-628021306. Now sir if it seems okay to you please merge my pull request.

2021-04-30 20:48 UTC, tarun26091999 requested changes
link it in the folder

2021-05-01 00:48 UTC, krishna-NIT commented
@rk05-lenavo  you haven't pushed your changes here, do it in this or and what is m and n?

2021-05-01 03:33 UTC, krishna-NIT commented
don't create 2 pr for single issue

2021-05-01 07:06 UTC, rk05-lenavo commented
@krishna-NIT @tarun26091999  Sir is it okay now.

2021-05-01 10:33 UTC, krishna-NIT commented
> @krishna-NIT @tarun26091999 Sir is it okay now.

No, 8742881915 Message me, here it will be difficult for communicating faster @rk05-lenavo

2021-05-01 12:37 UTC, plazzy99 commented
> > @krishna-NIT @tarun26091999 Sir is it okay now.
> 
> No, 8742881915 Message me, here it will be difficult for communicating faster @rk05-lenavo 

@krishna-NIT please dont share your personal contact no.

2021-05-01 12:39 UTC, krishna-NIT commented
> > > @krishna-NIT @tarun26091999 Sir is it okay now.
> > 
> > 
> > No, 8742881915 Message me, here it will be difficult for communicating faster @rk05-lenavo
> 
> @krishna-NIT please dont share your personal contact no.

ok but there are lot more issues how to convey them?

2021-05-01 12:40 UTC, krishna-NIT commented
> > > @krishna-NIT @tarun26091999 Sir is it okay now.
> > 
> > 
> > No, 8742881915 Message me, here it will be difficult for communicating faster @rk05-lenavo
> 
> @krishna-NIT please dont share your personal contact no.

ok , sorry sir

2021-05-01 12:42 UTC, krishna-NIT commented on Code/C++/Intersection_point_of_linked_list.cpp
> +// C++ program to get intersection point of two linked list
Describe the issue and Explain your approach in brief

2021-05-01 12:42 UTC, krishna-NIT commented on Code/C++/Intersection_point_of_linked_list.cpp
> +// Time Complexity: O(m+n)
add what is m and n?

2021-05-03 11:04 UTC, rk05-lenavo commented
@krishna-NIT Sir is it okay now.

2021-05-03 11:09 UTC, krishna-NIT commented
@rk05-lenavo Nice, just update the readme present in linklist folder.
just add this issue name and its location at the bottom side of the readme

2021-05-03 13:27 UTC, rk05-lenavo commented
@krishna-NIT Sir I'm new at github so can you Please tell me how I can update readme.md file from here.

2021-05-03 21:30 UTC, plazzy99 commented
> @krishna-NIT Sir I'm new at github so can you Please tell me how I can update readme.md file from here.
> 

Follow the pinned issue it contains a video that will help you

2021-05-04 05:32 UTC, rk05-lenavo commented
@krishna-NIT Sir is it Okay now.

2021-05-04 06:09 UTC, krishna-NIT commented
yes @rk05-lenavo  readme updated properly, just resolve the conflict

2021-05-04 06:16 UTC, rk05-lenavo commented
@krishna-NIT Sir is it okay now.

2021-05-04 06:18 UTC, krishna-NIT commented
Yes @rk05-lenavo ,
@rish-singhal LGTM, Please Merge it

2021-05-04 06:32 UTC, merged

2021-05-04 13:33 UTC, rk05-lenavo commented
@krishna-NIT Sir but till now there is no increment in the leaderboard pull request.