Minimum merge operation in array to make it palindrome
Algo-Phantoms/Algo-Tree pull request #1567
Opened 2021-04-08 19:00 UTC by Aarti002

issue #780 solved
Please @tarun26091999 review and merge my code!
Thank you!

2021-05-22 14:13 UTC, Rohan27s requested changes

2021-05-22 14:13 UTC, Rohan27s commented on Array/Python/merge_to_palindrome.py
> +#                                       ---->in next input line user have to provide space seperated integers
Remove the unnecessary space

2021-05-22 14:13 UTC, Rohan27s commented on Array/Python/merge_to_palindrome.py
> +#e.g-1)
Write Test Case 1 instead of eg 1

2021-05-23 10:38 UTC, Aarti002 commented
@Rohan27s i have made required changes please can you review again.

2021-05-24 13:58 UTC, Rohan27s commented
Resolve the conflicts

2021-05-25 11:11 UTC, Aarti002 commented
@Rohan27s i resolved it.
Thank you!

2021-05-29 14:38 UTC, merged