Create PalindromeCheck.cpp
Algo-Phantoms/Algo-Tree pull request #1568
Opened 2021-04-08 20:32 UTC by AnushkaS09

Check if the linked list is palindrome or not if yes return true if not return false. Linked list has to be taken as an input from the user.
ISSUE: #1340

2021-04-24 16:05 UTC, AnushkaS09 commented
@tarun26091999 @plazzy99 @rudrakshi99 Please review

2021-04-30 14:52 UTC, rish-singhal requested changes

2021-04-30 14:52 UTC, rish-singhal commented on Linked_list/PalindromeCheck.cpp
> +
remove extra lines

2021-04-30 14:52 UTC, rish-singhal commented on Linked_list/readme.md
> +* Palindrome Check---->[C++](/Linked_list/PalindromeCheck.cpp)
sort this list in alphabetical order

2021-04-30 14:52 UTC, rish-singhal commented on Linked_list/PalindromeCheck.cpp
> +  Node *temp = reverse(help);
use proper indentation of 1 tab or 4 spaces!

2021-04-30 14:52 UTC, rish-singhal commented on Linked_list/PalindromeCheck.cpp
> +    Node *new_head = reverse(save->next);
add appropriate comments explaining your algorithm and what variable does

2021-04-30 14:52 UTC, rish-singhal commented on Linked_list/PalindromeCheck.cpp
> +Node* reverse(Node *save)
add spaces here

2021-04-30 14:52 UTC, rish-singhal commented on Linked_list/PalindromeCheck.cpp
> +SAMPLE TEST CASE 1:
make the code interactive!

2021-05-23 18:42 UTC, tarun26091999 commented
main function is not present

2021-05-24 18:17 UTC, rish-singhal requested changes

2021-05-24 18:17 UTC, rish-singhal commented on Linked_list/PalindromeCheck.cpp
> +           Node *help=head;
add spaces around =

2021-05-24 18:17 UTC, rish-singhal commented on Linked_list/PalindromeCheck.cpp
> +           if(head==NULL){
add spaces around ==

2021-05-24 18:17 UTC, rish-singhal commented on Linked_list/PalindromeCheck.cpp
> +           while(temp && help){
add space after while(){ ===> i.e. while() {...

Do this with every if and while conditions in the code

2021-05-24 18:17 UTC, rish-singhal commented on Linked_list/PalindromeCheck.cpp
> +Node *takeinput()
add an empty line here

2021-05-24 18:17 UTC, rish-singhal commented on Linked_list/readme.md
> +* Palindrome Check---->[C++](/Linked_list/PalindromeCheck.cpp)
sort complete list .

2021-05-25 04:55 UTC, merged