Largest bst
Algo-Phantoms/Algo-Tree pull request #1569
Opened 2021-04-08 21:11 UTC by AnushkaS09

finding the largest BST in a given Binary Tree. Using C++
ISSUE #1355

2021-04-24 15:59 UTC, AnushkaS09 commented
@plazzy99 @tarun26091999 @rudrakshi99 Please review

2021-04-30 14:47 UTC, rish-singhal commented on Tree/LargestBST.cpp
> +    return isbst(root,INT_MIN,INT_MAX);
give spaces ","

2021-04-30 14:48 UTC, rish-singhal commented on Tree/LargestBST.cpp
> +/*Find the BST with the maximum heigth i.e. largest BST of the binary tree, which the user will input.*/
add information about the algorithm

2021-04-30 14:48 UTC, rish-singhal commented on Tree/LargestBST.cpp
> +    }
add appropriate comments in the code explaining the algorithm

2021-05-24 05:27 UTC, rish-singhal commented
Add proper indentation, with spaces around >>,<<,= operators

2021-05-24 06:08 UTC, rish-singhal requested changes

2021-05-24 06:08 UTC, rish-singhal commented on Tree/LargestBST.cpp
> +    cout<<"enter the root data:";
update it here.

2021-05-24 06:08 UTC, rish-singhal commented on Tree/LargestBST.cpp
> +    }
this too

2021-05-24 06:08 UTC, rish-singhal commented on Tree/LargestBST.cpp
> +int height(BinaryTreeNode<int> *root)  //returnning heigth of the tree
this is just the information about what it returns or what the function do, but how it does it is missing.

2021-05-24 15:52 UTC, rish-singhal requested changes

2021-05-24 15:52 UTC, rish-singhal commented on Tree/readme.md
>  * Lowest common ancestor in a binary tree ----> [Python](/Code/Python/LCA_in_binary_tree.py)
sort this list

2021-05-24 17:50 UTC, rish-singhal requested changes

2021-05-24 17:50 UTC, rish-singhal commented on Tree/readme.md
>  * Bottom-View of a Binary tree ----> [C++](/Code/C++/bottomView.cpp)
Still it is not sorted.

2021-05-24 18:09 UTC, merged