Issue#1247 Code Added
Algo-Phantoms/Algo-Tree pull request #1573
Opened 2021-04-09 07:59 UTC by Nikitha2309

There are two singly linked lists in a system. The end node of one of the linked list got linked to the second list, forming an inverted Y-shaped list. Write a program to get the point where two linked lists merge in Python

Fixes #1247

2021-04-09 08:00 UTC, Nikitha2309 commented
@raksha009 
Pls review this PR 
Thank You

2021-04-10 07:20 UTC, Nikitha2309 commented
@plazzy99 @raksha009 
Pls review this PR
Thank you

2021-04-15 13:14 UTC, Nikitha2309 commented
Respected @tarun26091999 
Please assign this issue to some other else and make it reviewed
I have written a clean code with comments and made all necessary changes.

It has been so long since I posted this PR , but no one reviewed this yet
Bcoz of this I am getting Branch conflicts
So Please REVIEW THIS PR 
Thank you

2021-04-15 13:50 UTC, tarun26091999 commented on Code/Python/linked_lists_intersection.py
> +Code works fine for all corner test cases tested , including null linked lists.
remove these lines

2021-04-15 13:52 UTC, tarun26091999 requested changes
add one more testcase.

2021-04-15 13:52 UTC, Nikitha2309 commented on Code/Python/linked_lists_intersection.py
> +Code works fine for all corner test cases tested , including null linked lists.
Done

2021-04-15 14:06 UTC, Nikitha2309 commented
Requested Changes Done @tarun26091999 
Let me know if there is anything else to be done
Merge if there are none
Thank you

2021-04-15 14:52 UTC, rudrakshi99 approved these changes

2021-04-15 14:52 UTC, merged