Kth max array
Algo-Phantoms/Algo-Tree pull request #1576
Opened 2021-04-09 08:24 UTC by vedant-jain03

2021-04-12 16:08 UTC, krishna-NIT requested changes

2021-04-12 16:08 UTC, krishna-NIT commented on Code/C++/Kth_maximum_in_array.cpp
> +
Include sort Function which is mentioned above

2021-04-12 16:34 UTC, vedant-jain03 reviewed
Updated with Sort function

2021-04-12 19:35 UTC, tarun26091999 commented on Array/readme.md
> -
you cannot remove these lines.

2021-04-12 19:37 UTC, tarun26091999 requested changes
this is not the most optimized approach. You took this long to raise the PR and still the solution nowhere near to the required quality. Also there are conflicts in code base.

2021-04-13 03:04 UTC, vedant-jain03 commented
> this is not the most optimized approach. You took this long to raise the PR and still the solution is nowhere near to the required quality. Also there are conflicts in code base.

Should I use heap to implement this?

2021-05-07 16:02 UTC, rudrakshi99 commented
> > this is not the most optimized approach. You took this long to raise the PR and still the solution is nowhere near to the required quality. Also there are conflicts in code base.
> 
> Should I use heap to implement this?

Yes

2021-05-31 15:39 UTC, closed without merging