Square Root Added #920 Solved with Readme
Algo-Phantoms/Algo-Tree pull request #1587
Opened 2021-04-10 08:57 UTC by krishna-NIT

#920 Done in Java
@nakul-19 @rudrakshi99 @OjusWiZard Please Review it All Changes are Done.

2021-04-27 03:11 UTC, krishna-NIT commented
@yasharth291 Please review it because Daily I get Conflicts in Readme File, I have to Resolve them Daily, Am I making any Mistake in Readme ?, can you please tell me why I am Getting Conflicts in Readme always, coz I am new to GIT and GITHUB

2021-04-28 14:05 UTC, krishna-NIT commented
@yasharth291 will you please review it !

2021-05-22 13:31 UTC, krishna-NIT commented
@Rohan27s @tarun26091999  Please Review it and Let me Know if any changes

2021-05-24 14:02 UTC, Rohan27s requested changes

2021-05-24 14:02 UTC, Rohan27s commented on Code/Java/sqrt.java
> +        Time Complexity: O(log n)
mention the value of n here

2021-05-24 14:45 UTC, krishna-NIT commented
@Rohan27s Done Sir!

2021-05-24 15:47 UTC, krishna-NIT commented
@rish-singhal Last remaning sir

2021-05-24 15:49 UTC, merged