Implement Painter's Partition Problem (Binary Search)
Algo-Phantoms/Algo-Tree pull request #1593
Opened 2021-04-10 14:58 UTC by rk05-lenavo

#599 Fixed Issue

2021-04-19 17:13 UTC, rudrakshi99 requested changes

2021-04-19 17:13 UTC, rudrakshi99 commented on Code/C++/ Implement_Painter's_Partition.cpp
> +	int n = sizeof(arr) / sizeof(arr[0]);
make it user input

2021-04-19 17:13 UTC, rudrakshi99 commented on Code/C++/ Implement_Painter's_Partition.cpp
> +#include <climits>
add a brief description of algo

2021-04-19 17:13 UTC, rudrakshi99 commented on Code/C++/ Implement_Painter's_Partition.cpp
> +// Output: 20
add atleast 2 test cases and complexities

2021-04-19 17:14 UTC, rudrakshi99 commented
Please follow proper guidelines and also update the readme of sorting_searching folder.

2021-05-04 06:17 UTC, rk05-lenavo commented
@rudrakshi99 mam is it okay now.

2021-05-31 07:23 UTC, rk05-lenavo commented
@rudrakshi99 mam can you check

2021-05-31 07:24 UTC, rk05-lenavo commented
@rudrakshi99 I have been requesting to you to see the code for so long.

2021-05-31 15:35 UTC, Rohan27s commented
Plagiarism from https://www.geeksforgeeks.org/painters-partition-problem-set-2/ (you have just changed variable names)

2021-05-31 15:35 UTC, closed without merging