Finding the negative cycle in a graph
Algo-Phantoms/Algo-Tree pull request #1611
Opened 2021-04-12 05:57 UTC by shiv-30

Issue #535 Solved
Python code is added with proper explanation, indentation, time complexity and text cases.

2021-04-23 08:34 UTC, Rohan27s requested changes
The code and test cases are fine, just remove all unnecessary spaces in the whole program

2021-04-23 08:34 UTC, Rohan27s commented on Code/Python/negative_cycle_in_a_graph.py
> +# Program to find the negative cycle in the graph
Add multi-line comment using ''' instead of using # for single line comment

2021-04-23 08:34 UTC, Rohan27s commented on Code/Python/negative_cycle_in_a_graph.py
> +# Time Complexity: O(V*E)
Add this time complexity at the end of the code

2021-04-23 08:34 UTC, Rohan27s commented on Code/Python/negative_cycle_in_a_graph.py
> +
Remove unnecessary blank space

2021-04-23 08:35 UTC, Rohan27s commented
Also, update the readme

2021-05-13 05:19 UTC, shiv-30 commented on Code/Python/negative_cycle_in_a_graph.py
> +
All changes are done

2021-05-31 16:17 UTC, Rohan27s commented
Readme wasn't updated

2021-05-31 16:17 UTC, closed without merging