Manachers algo Added #758
Algo-Phantoms/Algo-Tree pull request #1623
Opened 2021-04-13 10:41 UTC by krishna-NIT

#785 done in java
Manacher’s Algorithm – Linear Time Longest Palindromic Substring added
Please Review

2021-04-25 17:23 UTC, rish-singhal requested changes

2021-04-25 17:23 UTC, rish-singhal commented on Code/Java/longPalindrome.java
> +        Time Complexity: O(n)
describe what is n here

2021-04-25 17:23 UTC, rish-singhal commented on Code/Java/longPalindrome.java
> +        }
give appropriate line breaks to make the code more readable.

2021-04-25 17:23 UTC, rish-singhal commented on string/readme.md
> +* Manacher's algorithm (finding the longest palindrome in a string) ----> [Java](/Code/Java/longPalindrome.java)
Sort the list in alphabetical order

2021-04-27 04:32 UTC, rish-singhal commented on string/readme.md
> +* Manacher's algorithm (finding the longest palindrome in a string) ----> [Java](/Code/Java/longPalindrome.java)
Update this*

2021-04-27 04:32 UTC, rish-singhal commented on Code/Java/longPalindrome.java
> +        Time Complexity: O(n)
This too

2021-04-27 04:33 UTC, rish-singhal commented
Hey do look at the review comments

2021-04-27 12:05 UTC, rish-singhal commented
Describe what n is.

2021-04-27 12:26 UTC, krishna-NIT commented
Thanks for Reviewing it and Sorry for Delay from my side, @rish-singhal 
New Changes Done!

2021-04-27 12:34 UTC, rish-singhal approved these changes

2021-04-27 12:34 UTC, rish-singhal commented
Great!

2021-04-27 12:34 UTC, merged