Added Trapping Rainwater problem in python
Algo-Phantoms/Algo-Tree pull request #1635
Opened 2021-04-14 06:33 UTC by Shalvi-Singhal

#594 fixed.
@tarun26091999 @plazzy99 please review it.

2021-04-22 15:30 UTC, Rohan27s commented
@Shalvi-Singhal Add print statements that will ask for the size and values of the array from the users

2021-04-24 05:58 UTC, Shalvi-Singhal commented
> @Shalvi-Singhal Add print statements that will ask for the size and values of the array from the users

I have added the print statements @Rohan27s please review it.

2021-04-24 06:07 UTC, Rohan27s requested changes
Code if fine, just remove unnecessary space and add multiline comment

2021-04-24 06:07 UTC, Rohan27s commented on Code/Python/trapping_rainwater.py
> +# Problem Description:
use ''' and the comments into multiline comments instead of using # again and again

2021-04-24 07:13 UTC, Shalvi-Singhal commented
Changes made.
@Rohan27s

2021-04-24 07:15 UTC, Rohan27s approved these changes
Nice Work, thanks for your contribution!

2021-04-24 07:17 UTC, merged

2021-04-24 07:20 UTC, Shalvi-Singhal commented
Thank you!