Union of two array
Algo-Phantoms/Algo-Tree pull request #1691
Opened 2021-04-22 17:42 UTC by Mugdha-Hazra

Added code for finding the Union Of Two Arrays, @tarun26091999 sir can you please review my code.

2021-04-23 11:03 UTC, rish-singhal commented
Please mention the issue number.

2021-04-23 12:50 UTC, Mugdha-Hazra commented
issue no. is #739

2021-04-25 01:44 UTC, rish-singhal requested changes

2021-04-25 01:44 UTC, rish-singhal commented on Code/C++/Generate_all_valid_parentheses.cpp
> +Constraints:
Can you please remove this file, as it is not the part of the ISSUE

2021-04-25 01:44 UTC, rish-singhal commented on Code/C++/finding_all_subsets.cpp
> +FINDING ALL THE SUBSET OF THE ARRAY/VECTOR BY USING BACKTRACKING
Remove this file too

2021-04-25 01:44 UTC, rish-singhal commented on Code/C++/Union_of_two_unsorted_array.cpp
> +Sample Output
Give time complexity and at least one more test case

2021-04-25 01:44 UTC, rish-singhal commented on Code/C++/Union_of_two_unsorted_array.cpp
> +Time Complexity: O(m+n)
This is not O(m+n) as you are using set, for inserting something in set it takes O(log n) time complexity.

So, please update it accordingly and shift this to the bottom of the code.

2021-04-25 01:44 UTC, rish-singhal commented
Also, update read me adding link to this file.

2021-04-25 04:33 UTC, Mugdha-Hazra commented
Hello @rish-singhal  sir, I had tried to make all the changes that you had sited above but I'm a Lil confused about where to edit the readme can you please help me out as I'm a complete noob in this field, also can you please review the changes that I had made.

2021-04-25 04:57 UTC, rish-singhal commented
This is the link to the [readme](https://github.com/Algo-Phantoms/Algo-Tree/tree/main/Array)

2021-04-25 04:59 UTC, rish-singhal requested changes

2021-04-25 04:59 UTC, rish-singhal commented on Code/C++/Union_of_two_unsorted_array.cpp
> +Time Complexity: O(log n)
Time complexity is O((n+m) log(n+m))

2021-04-25 05:40 UTC, Mugdha-Hazra commented
@rish-singhal sir I had updated the readme.

2021-04-25 06:01 UTC, rish-singhal commented
hey don't create another PR for this. Update readme in this PR only.

2021-04-25 06:23 UTC, Mugdha-Hazra commented
@rish-singhal sir can you please guide me on how to update this pr for updating the readme?

2021-04-25 06:27 UTC, rish-singhal commented
Update the readme in this branch of yours only.

2021-04-25 14:55 UTC, Mugdha-Hazra commented
Hello @rish-singhal sir, I tried a lot to update the readme but I'm facing some errors can you plz help me to resolve these issues.

2021-04-25 15:04 UTC, Mugdha-Hazra commented
Hello @rish-singhal sir, I finally updated the readme.

2021-04-25 15:24 UTC, rish-singhal requested changes

2021-04-25 15:24 UTC, rish-singhal commented on Code/C++/Union_of_two_unsorted_array.cpp
> +First of all here we'll initialize an empty hash set 's'.
Hey just remove the word hash, as set is not a hash based data structure. Then your code is ready to merge!

2021-04-25 15:30 UTC, Mugdha-Hazra commented
I removed the hash word

2021-04-25 15:36 UTC, merged

2021-04-25 15:36 UTC, Mugdha-Hazra commented
Thank you soo much @rish-singhal  sir for your guidance and support today I learned a lot about Git and GitHub and successfully able to make my first open-source contribution.

2021-04-25 15:38 UTC, rish-singhal commented
Great, all the best for your open source journey :)