Added the swap even and odd bits algorithm in python.
Algo-Phantoms/Algo-Tree pull request #1705
Opened 2021-04-24 05:12 UTC by anishsingh42

Swap Even and Odd Bits is added to the python folder.
Code path added in readme.md file of Bit-Manipulation folder.

Issue Number: #1201 
Language Used : Python

@rish-singhal @plazzy99 @tarun26091999 , I request to please check my PR once. 
Please let me know if any changes are required. 
Thank you

2021-04-25 01:36 UTC, rish-singhal commented
There are some conflicts, please resolve it.

2021-04-25 01:39 UTC, rish-singhal requested changes

2021-04-25 01:39 UTC, rish-singhal commented on Code/Python/Swap_even_odd_bits.py
> +print("The output for",int_number,"after swapping even and odd bits is:",swap_even_odd_bits(int_number))
Add a space after comma ,

2021-04-25 01:39 UTC, rish-singhal commented on Code/Python/Swap_even_odd_bits.py
> +print("The output for",int_number,"after swapping even and odd bits is:",swap_even_odd_bits(int_number))
Here also

2021-04-25 01:39 UTC, rish-singhal commented on Code/Python/Swap_even_odd_bits.py
> +Since we require fininte number of steps in computing the solution which doesnot grow with the input varaible "int_number" , hence we get the time complexity of order 1 that is constant time.
Break this line into 2-3 lines

2021-04-25 01:39 UTC, rish-singhal commented on Code/Python/Swap_even_odd_bits.py
> +The space remains constant throughout, hence the space complexity is also O(1) that is constant space.
This too.

2021-04-25 05:21 UTC, Rohan27s requested changes
Don't write a full essay in the description. Kindly keep it small

2021-04-25 05:50 UTC, anishsingh42 commented on Code/Python/Swap_even_odd_bits.py
> +We need to right shift the even bits by 1 to make them odd bits.
It is because of explaining the code step by step. That has caused the description to be lengthy.

2021-04-25 05:54 UTC, Rohan27s commented on Code/Python/Swap_even_odd_bits.py
> +We need to right shift the even bits by 1 to make them odd bits.
Just give a brief description about the code

2021-04-25 12:47 UTC, Rohan27s approved these changes

2021-04-27 03:12 UTC, anishsingh42 commented
@rish-singhal Please review my changes.
Thank you

2021-04-27 04:30 UTC, rish-singhal commented
If possible truncate the explanation part or add a reference?

2021-04-27 05:05 UTC, anishsingh42 commented
I have already reduced a lot of explanation earlier, further reduction in description might make the understanding part difficult. 

@rish-singhal 

> If possible truncate the explanation part or add a reference? Otherwise it's good to go

2021-04-27 05:07 UTC, rish-singhal commented
Okay then

2021-04-27 05:07 UTC, merged