Added code for Squareroot(python)
Algo-Phantoms/Algo-Tree pull request #1709
Opened 2021-04-24 08:35 UTC by Sathwika-02

@tarun26091999 @rudrakshi99 Please review this PR .This is solve issue #920

2021-04-25 17:21 UTC, rish-singhal commented
please resolve the conflicts, also use pylint once and try to get the score to 10

2021-05-30 07:29 UTC, rudrakshi99 requested changes

2021-05-30 07:29 UTC, rudrakshi99 commented on Code/Python/squareroot.py
> +
add complexities at the end

2021-05-30 18:01 UTC, rish-singhal requested changes

2021-05-30 18:01 UTC, rish-singhal commented on Algorithm/Number_theory/readme.md
>  - Counting number of digits in factorial using Kamenetsky's Formula ----> [Java](Code/Java/Kamenetsky_Formula.java)
combine and sort this list!

2021-05-31 11:15 UTC, rish-singhal requested changes

2021-05-31 11:15 UTC, rish-singhal commented on Algorithm/Number_theory/readme.md
>  - Fibonacci Series ----> [Java](/Code/Java/Fibonacci_Series.java)
Why there are 2 headings with the same name. Merge them.

2021-05-31 16:11 UTC, rish-singhal commented on Algorithm/Number_theory/readme.md
>  - Fibonacci Series ----> [Java](/Code/Java/Fibonacci_Series.java)
remove the above one!

2021-06-01 08:15 UTC, closed without merging

2021-06-01 08:16 UTC, rish-singhal commented
Not a valid PR