Trimorphic Number in Python #1736
Algo-Phantoms/Algo-Tree pull request #1747
Opened 2021-04-26 14:35 UTC by U-c0de

Completed issue : Trimorphic number in Python

2021-04-27 13:04 UTC, U-c0de commented
Completed issue : Trimorphic number in Python #1736

2021-04-28 07:09 UTC, U-c0de commented
Please Check --- @rish-singhal @yasharth291 @raksha009 @rudrakshi99 @plazzy99 @OjusWiZard @tarun26091999 @Rohan27s

2021-04-29 06:19 UTC, U-c0de commented
@Rohan27s @rish-singhal  check this

2021-04-29 06:22 UTC, Rohan27s requested changes
Update readme first

2021-04-29 06:25 UTC, U-c0de commented
@Rohan27s  Done

2021-04-29 06:33 UTC, Rohan27s requested changes

2021-04-29 06:33 UTC, Rohan27s commented on Code/Python/TrimorphicNumber.py
> +            The given number is Trimorphic
fix this, 20 is not a trimorphic num

2021-04-29 07:11 UTC, U-c0de commented
Done @Rohan27s

2021-04-29 09:04 UTC, Rohan27s approved these changes

2021-04-29 09:05 UTC, merged