finding subtree size of each node
Algo-Phantoms/Algo-Tree pull request #1748
Opened 2021-04-26 14:35 UTC by Tanya933

issue #1226  fixed . @tarun26091999 @rudrakshi99 @plazzy99 @nakul-19  Please review the PR .Thankyou

2021-05-01 12:49 UTC, krishna-NIT commented on Code/C++/subtree_size.cpp
> +
Mention Space And Time Complexity Here

2021-05-01 12:51 UTC, Tanya933 commented on Code/C++/subtree_size.cpp
> +
okay working on it.

2021-05-01 12:52 UTC, krishna-NIT commented
@Tanya933  Delete the file that You have added to this location (Code/C++/a.out)
Update Readme of Related problem, if you got confused about where to update just
Refer to any merged pr and follow that. Just add your issue name with its location at end of the readme in questions Section

2021-05-01 13:00 UTC, Tanya933 commented
okay @krishna-NIT

2021-05-01 13:02 UTC, krishna-NIT commented
I Think you haven't pushed your changes

2021-05-01 13:04 UTC, krishna-NIT commented
> I Think you haven't pushed your changes

@Tanya933  Check it once

2021-05-01 14:59 UTC, Tanya933 commented
@krishna-NIT  Please review the PR.Thankyou

2021-05-01 15:11 UTC, krishna-NIT commented
@rish-singhal LGTM

2021-05-14 08:00 UTC, Tanya933 commented
issue #1226 fixed . @tarun26091999 @rudrakshi99 @plazzy99 @nakul-19 @rish-singhal  .Please merge this issue .Thankyou

2021-05-18 19:07 UTC, tarun26091999 requested changes
remove the example from top.

2021-05-18 19:07 UTC, tarun26091999 commented on Code/C++/subtree_size.cpp
> +
complexities have to come at bottom.

2021-05-18 19:07 UTC, tarun26091999 commented
also resolve the conflict.

2021-05-19 04:24 UTC, Tanya933 commented
@tarun26091999 .Removed example from top ,moved the complexity at the bottom and resolved the conflicts.Please review .Thankyou

2021-05-29 16:03 UTC, rish-singhal commented
Resolve conflicts

2021-05-30 06:45 UTC, closed without merging