program for calculating nCr added in python language
Algo-Phantoms/Algo-Tree pull request #1756
Opened 2021-04-27 05:00 UTC by dhruvdy

2021-04-27 05:00 UTC, dhruvdy commented
Issue #664

2021-04-27 12:55 UTC, rish-singhal requested changes

2021-04-27 12:55 UTC, rish-singhal commented on Algorithm/Number_theory/readme.md
>  - Factorial of a number without recursion ---->[Python](/Code/Python/factorial_without_recursion.py)
sort this list in alphabetical order

2021-04-27 12:55 UTC, rish-singhal commented on Code/Python/calculate_the_value_of_nCr.py
> +
remove extra lines

2021-04-27 12:55 UTC, rish-singhal commented on Code/Python/calculate_the_value_of_nCr.py
> +def gcd(num1,num2):             #This function is for calculating greatest common divisor
dont give this much space between comment and def, rather use docstring for the function i.e.

```python
def func():
    """ XYZ.... """
```

do this for all the functions in this file

2021-04-27 12:55 UTC, rish-singhal commented on Code/Python/calculate_the_value_of_nCr.py
> +    if num2==0:
give spaces around "," "=",.... and all

2021-04-27 12:55 UTC, rish-singhal commented on Code/Python/calculate_the_value_of_nCr.py
> +        divisor=gcd(numerator,denominator)
here to give spaces

2021-04-27 12:55 UTC, rish-singhal commented on Code/Python/calculate_the_value_of_nCr.py
> +Time complexity : O(rlog(n))
what is r and n, describe here

2021-04-27 12:55 UTC, rish-singhal commented on Code/Python/calculate_the_value_of_nCr.py
> +r=int(r)
give spaces

2021-04-30 14:25 UTC, rish-singhal requested changes

2021-04-30 14:25 UTC, rish-singhal commented
solve merge conflicts

2021-05-01 04:41 UTC, closed without merging