Toeplitz
Algo-Phantoms/Algo-Tree pull request #1763
Opened 2021-04-27 11:12 UTC by krishna-NIT

Fixes #1231 
@tarun26091999 @yasharth291
Please Review it !

2021-04-27 12:37 UTC, krishna-NIT commented
@rish-singhal  Please Review it sir !

2021-04-27 12:43 UTC, rish-singhal requested changes

2021-04-27 12:43 UTC, rish-singhal commented on 2D_Array/readme.md
> +* Checking Teoplitz Matrix Algorithm ----> [Java](/Code/Java/Toeplitz.java)
Sort this list in lexographical order.

2021-04-27 12:43 UTC, rish-singhal commented on Code/Java/Toeplitz.java
> +package tmatrix;
add extra line here

2021-04-27 12:43 UTC, rish-singhal commented on Code/Java/Toeplitz.java
> +        for (int i = 0;i<l;i++){
give proper spaces after ";"

2021-04-27 12:43 UTC, rish-singhal commented on Code/Java/Toeplitz.java
> +        for (int i = 0;i<clen;i++){
here too

2021-04-27 12:43 UTC, rish-singhal commented on Code/Java/Toeplitz.java
> +            for (int j = i+1;j<clen && temp<rlen;j++){
here too, and other places

2021-04-27 12:43 UTC, rish-singhal commented on Code/Java/Toeplitz.java
> +                if (val!=matrix[j][temp]){
and here,

2021-04-27 12:43 UTC, rish-singhal commented on Code/Java/Toeplitz.java
> +        Time Complexity: O(n^2)
describe what n is

2021-04-27 12:56 UTC, krishna-NIT commented
Thanks for Reviewing @rish-singhal , And From Now Onwards I will Keep this Habit of giving Space, sorry for that, Thank You !

2021-04-27 12:57 UTC, krishna-NIT commented
> Thanks for Reviewing @rish-singhal , And From Now Onwards I will Keep this Habit of giving Space, sorry for that, Thank You !

@rish-singhal Changes done !

2021-04-29 10:18 UTC, rish-singhal requested changes

2021-04-29 10:18 UTC, rish-singhal commented on Code/Java/Toeplitz.java
> +                if (val!=matrix[temp][j]){
can you update these?

2021-04-29 10:18 UTC, rish-singhal commented on Code/Java/Toeplitz.java
> +        for (int i = 0; i<clen; i++){
here too 
around "<"

2021-04-29 10:18 UTC, rish-singhal commented on Code/Java/Toeplitz.java
> +
remove extra lines

2021-04-29 10:40 UTC, krishna-NIT commented
@rish-singhal changes made successfully, please review it

2021-04-29 10:46 UTC, merged

2021-05-28 02:02 UTC, krishna-NIT commented
@rish-singhal Sir
Please See Discord Once!