GCD PYTHON CODE
Algo-Phantoms/Algo-Tree pull request #1769
Opened 2021-04-27 15:01 UTC by Shraddha13Jain

python code of GCD of 2 numbers .

2021-04-27 15:04 UTC, Shraddha13Jain commented
issue [https://github.com/Algo-Phantoms/Algo-Tree/issues/559]
PR [https://github.com/Algo-Phantoms/Algo-Tree/pull/1769]

2021-04-28 14:09 UTC, tarun26091999 requested changes
link it to Algorithm/number_theory folder

2021-04-28 14:31 UTC, Shraddha13Jain commented
@tarun26091999 done the changes requested.

2021-04-28 15:03 UTC, tarun26091999 approved these changes

2021-04-28 15:04 UTC, merged