Balanced Bracket Problem
Algo-Phantoms/Algo-Tree pull request #1775
Opened 2021-04-27 16:24 UTC by Prerna-07

closes : #1683

2021-04-27 16:24 UTC, Prerna-07 commented
@Rohan27s pls check once more i have created everything one more

2021-04-27 16:34 UTC, yasharth291 approved these changes

2021-04-28 06:07 UTC, Rohan27s requested changes

2021-04-28 06:07 UTC, Rohan27s commented on Stack/Balanced Bracket Problem.Java
> +
Remove unnecessary spaces

2021-04-28 06:07 UTC, Rohan27s commented on Tree/readme.md
> -* Searching in BST ----> [C++](/Code/C++/searching_in_bst.cpp)
Unnecessary commit you just need to edit Readme of Stack

2021-04-28 06:53 UTC, Rohan27s approved these changes

2021-04-28 06:55 UTC, Rohan27s commented
Why have you deleted tree/Readme in your commit. I asked you to remove the commit of the read me file, not to delete the tree/readme file in your commit

2021-04-28 06:58 UTC, Prerna-07 commented
@Rohan27s sorry i am trying to getting it back

2021-04-28 07:07 UTC, Prerna-07 commented
@Rohan27s i have restored the readme file. Pls guide me how to remove that commmit

2021-04-28 08:10 UTC, Prerna-07 commented
@Rohan27s I have resolved the problem pls check.

2021-04-28 14:00 UTC, Prerna-07 commented
@Rohan27s ok sir

2021-04-28 14:00 UTC, closed without merging

2021-04-28 14:36 UTC, Prerna-07 commented
@Rohan27s  if i delete my repository will it effect the merged issues?

2021-04-29 05:34 UTC, Rohan27s commented
No @Prerna-07

2021-04-29 05:41 UTC, Prerna-07 commented
@Rohan27s I have done all necessary changes pls check my pull request #1794.

2021-04-29 05:48 UTC, Rohan27s commented
@Prerna-07 don't comment on a closed pr. I will check it wait.