Stock Span Problem
Algo-Phantoms/Algo-Tree pull request #1796
Opened 2021-04-28 16:27 UTC by Prerna-07

Stock Span Problem
Explanation : Stock span is defined as the number of days passed between the current day and the first day before today when price was higher than today.

closes : #1684

2021-04-28 16:28 UTC, Prerna-07 commented
@nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99 pls check

2021-04-29 06:00 UTC, Rohan27s requested changes

2021-04-29 06:00 UTC, Rohan27s commented on Code/Java/Balanced Bracket Problem.java
> -It will be an iterative solution in which loop will iterate over each character of expression, if opening brackets encountered then simply push in stack, if closing brackets
Why have you deleted someone else's code? Revert it back

2021-04-29 06:04 UTC, Prerna-07 commented
@Rohan27s sorry sir it it my code i didn't deleted it.

2021-04-29 06:05 UTC, Prerna-07 commented
@Rohan27s added the file in this branch sir pls check.

2021-04-29 06:09 UTC, Rohan27s approved these changes

2021-04-29 06:09 UTC, merged