Sliding window maximum-->Closes: [#1750]
Algo-Phantoms/Algo-Tree pull request #1821
Opened 2021-04-29 17:24 UTC by Prerna-07

closes : #1750

2021-04-29 17:26 UTC, Prerna-07 commented
@nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99 pls check

2021-04-30 14:30 UTC, rish-singhal requested changes

2021-04-30 14:30 UTC, rish-singhal commented on Array/readme.md
> +- Union of two Arrays ----> [C++](Code/C++/Union_of_two_unsorted_array.cpp)
sort this list in lexicographic order

2021-04-30 14:30 UTC, rish-singhal commented on Code/Java/Sliding Window Maximum.java
> +Time Complexity: O(n)
describe n here

2021-04-30 14:30 UTC, rish-singhal commented on Code/Java/Sliding Window Maximum.java
> +       7
make this in one line, same with above test case

2021-04-30 14:48 UTC, Prerna-07 commented
@rish-singhal updated required changes pls check.

2021-05-08 13:19 UTC, Prerna-07 commented
@rish-singhal pls review it again i have updated the content.

2021-05-22 08:17 UTC, Prerna-07 commented
@nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99 pls review.

2021-05-24 15:47 UTC, rish-singhal commented
resolve conflicts

2021-05-24 16:39 UTC, Prerna-07 commented
@rish-singhal done pls check.

2021-05-24 18:28 UTC, rish-singhal requested changes

2021-05-24 18:28 UTC, rish-singhal commented on Code/Java/sliding_window_maximum.java
> +    for(int i=0;i<a.length-k+1;++i)       // sliding the window
give spaces around =, >, <,..... in whole code

2021-05-24 18:28 UTC, rish-singhal commented on Code/Java/sliding_window_maximum.java
> +Space Complexity: O(n)
add extra empty line at the end of the file

2021-05-25 05:26 UTC, Prerna-07 commented
@rish-singhal  done pls check

2021-05-25 16:57 UTC, Prerna-07 commented
@rish-singhal pls check this also

2021-05-25 16:59 UTC, rish-singhal commented on Code/Java/sliding_window_maximum.java
> +    for(int i=0;i<a.length-k+1;++i)       // sliding the window
Update this

2021-05-25 18:00 UTC, rish-singhal requested changes

2021-05-25 18:00 UTC, rish-singhal commented on Code/Java/sliding_window_maximum.java
> +        while(r[j]<i+k)                   // here j is the index of current maximum element and r[j] will give the index of next maximum element, while r[j] is in the window
This is not updated, add spaces

2021-05-25 18:01 UTC, rish-singhal commented
Hey please check my comments about giving appropriate spaces around operators.

2021-05-26 01:28 UTC, Prerna-07 commented
@rish-singhal  done pls check.

2021-05-26 01:30 UTC, merged