Prefix to postfix in cpp
Algo-Phantoms/Algo-Tree pull request #1828
Opened 2021-04-30 16:37 UTC by aaadddiii

Fixes issue #1819

2021-04-30 16:37 UTC, aaadddiii commented
@nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal please review it

2021-05-30 06:59 UTC, rish-singhal requested changes

2021-05-30 06:59 UTC, rish-singhal commented on Stack/readme.md
>  -   Stock Span Problem ----> [C++](/Code/C++/Stock_Span_Problem.cpp) | [Java](/Code/Java/Stock_Span_Problem.Java) | [Python](/Code/Python/StockSpan.py)
Sort this list.

2021-05-30 06:59 UTC, rish-singhal commented on Code/C++/Prefix_to_postfix.cpp
> +*+abc
Note.

2021-05-30 06:59 UTC, rish-singhal commented on Code/C++/Prefix_to_postfix.cpp
> +// prefixtopostfix function converts a prefix expression to postfix
Add empty line here

2021-05-30 06:59 UTC, rish-singhal commented on Code/C++/Prefix_to_postfix.cpp
> +// if operand function checks if the element is an operand
Add empty line here

2021-06-01 03:47 UTC, closed without merging