Delete without head pointer
Algo-Phantoms/Algo-Tree pull request #1870
Opened 2021-05-06 07:11 UTC by dikshajoshi18

2021-05-21 08:32 UTC, tarun26091999 commented
link issue.

2021-05-21 11:37 UTC, dikshajoshi18 commented
https://github.com/Algo-Phantoms/Algo-Tree/issues/659

On Fri, May 21, 2021 at 2:02 PM Tarun Yadav ***@***.***>
wrote:

> link issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Algo-Phantoms/Algo-Tree/pull/1870#issuecomment-845780311>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOBXJEI2B4THJYYBRPDY53DTOYLCDANCNFSM44GOCYHA>
> .
>

2021-05-30 08:26 UTC, tarun26091999 requested changes
display the message why last node can't be deleted.

2021-06-01 07:14 UTC, tarun26091999 approved these changes

2021-06-01 07:15 UTC, merged