check_prime added in JAVA
Algo-Phantoms/Algo-Tree pull request #188
Opened 2021-03-08 11:40 UTC by krishna-NIT

check_prime.java added
returns true if no is prime otherwise returns false
Necessary Comments included,
Sample Input, Output & Complexity included 
for issue assigned to  me #157
by ShriKrushna Bhagwat
GSSoC 21' Contributor

2021-03-08 18:00 UTC, krishna-NIT reviewed
#157 Solved @nakul-19 @rudrakshi99 @plazzy99 take a look to code

2021-03-09 05:41 UTC, krishna-NIT commented
@plazzy99 @rudrakshi99 Will you please help me with why my pull request showing actions needed,
please guide me

2021-03-10 14:09 UTC, plazzy99 requested changes
Code LGTM just make the requested changes

2021-03-10 14:09 UTC, plazzy99 commented on Code/Java/check_prime.java
> +Prime Numbers are those who dont's have any divisors other than 1 and itself,
bring this comment outside and at the top of the code

2021-03-11 13:26 UTC, raksha009 requested changes

2021-03-11 13:26 UTC, raksha009 commented on Code/Java/check_prime.java
> + */
Plz add a new line here.

2021-03-16 05:47 UTC, plazzy99 requested changes
You need to raise 2 separate issues for resolving 2 different pr else you will lose points

2021-03-16 05:47 UTC, plazzy99 commented on Array/peakval/peakvalueinarray.java
> +Here we will Assume Peak element in Array is array[0] i.e 1st value,
take this comment at the top of the code

2021-03-16 14:12 UTC, krishna-NIT commented
@plazzy99 all correction in #720,
I am new to GitHub so, done this crazy stuffs earlier, sorry for that
tell me if any changes

2021-03-16 14:12 UTC, closed without merging

2021-03-16 14:13 UTC, krishna-NIT commented
@plazzy99 all correction in #720,
I am new to GitHub so, done this crazy stuffs earlier, sorry for that
my correct new &b accurate pull request at #720 
tell me if any changes

2021-03-19 15:42 UTC, krishna-NIT commented
@raksha009 May I know, Why the tags are removed, I have done it in java & have made pull request