Knight tour ---> Closes : [#1849]
Algo-Phantoms/Algo-Tree pull request #1896
Opened 2021-05-09 15:51 UTC by Prerna-07

closes: #1849

2021-05-09 15:51 UTC, Prerna-07 commented
@nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99 pls check this PR.

2021-05-22 08:21 UTC, Prerna-07 commented
@nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99 pls check this PR.

2021-05-24 14:46 UTC, Prerna-07 commented
@nakul-19 @raksha009 @plazzy99 @tarun26091999 @rish-singhal @yasharth291 @Rohan27s @rudrakshi99 pls check this PR.

2021-05-24 15:45 UTC, rish-singhal requested changes

2021-05-24 15:45 UTC, rish-singhal commented on Algorithm/Backtracking/readme.md
>  * Sudoku Solver ----> [C++](/Code/C++/sudoku_solver.cpp) | [Java](/Code/Java/Sudoku_Solver.java)
Sort this list

2021-05-24 15:45 UTC, rish-singhal commented on Code/Java/Knights_Tour.java
> +       if(row<0 || row>=chess.length || col<0 || col>=chess.length || chess[row][col]!=0)  // check for invalid moves i.e if box is already visited, or for non exixting points
Give proper spaces around >,=,>>,<<,..... in whole file

2021-05-24 15:45 UTC, rish-singhal commented on Code/Java/Knights_Tour.java
> +Time Complexity : O(8^(N^2))
Describe what is N here

2021-05-24 16:45 UTC, Prerna-07 commented
@rish-singhal  done pls check.

2021-05-25 05:27 UTC, Prerna-07 commented
@rish-singhal  added extra line in this as well pls check.

2021-05-25 15:59 UTC, rish-singhal requested changes

2021-05-25 15:59 UTC, rish-singhal commented on Algorithm/Backtracking/readme.md
>  * Rat in a Maze ----> [C++](/Code/C++/rat_in_maze.cpp)
Sort this list

2021-05-25 15:59 UTC, rish-singhal commented on Code/Java/Knights_Tour.java
> +21 2 13 8 23
Code seems good to go

2021-05-25 15:59 UTC, rish-singhal commented on Code/Java/Knights_Tour.java
> +       if(row < 0 || row>=chess.length || col < 0 || col >= chess.length || chess[row][col] != 0)  // check for invalid moves i.e if box is already visited, or for non exixting points
Add space around >=,...

2021-05-25 15:59 UTC, rish-singhal commented on Code/Java/Knights_Tour.java
> +       printKnightsTour(chess, row-2, col+1, count+1); // solution is searching clock wise all these functions are calling row and columns accordingly
Here also add spaces around +,-,...

2021-05-25 16:09 UTC, Prerna-07 commented
@rish-singhal  done pls check

2021-05-25 16:40 UTC, rish-singhal commented on Code/Java/Knights_Tour.java
> +       if(row < 0 || row>=chess.length || col < 0 || col >= chess.length || chess[row][col] != 0)  // check for invalid moves i.e if box is already visited, or for non exixting points
This is not resolved

2021-05-25 16:40 UTC, rish-singhal commented
Just one more change

2021-05-25 16:57 UTC, Prerna-07 commented
@rish-singhal done pls check

2021-05-25 16:59 UTC, merged