Kahns Algorithm for issue #200 added
Algo-Phantoms/Algo-Tree pull request #209
Opened 2021-03-08 16:15 UTC by dhruvinfo28

Closes #200 .
Kahn's Algorithm added. Time and space complexity mentioned. Test cases are also given.

2021-03-08 18:55 UTC, tarun26091999 requested changes
you haven't linked it to proper folder. Go through the guidelines properly.

2021-03-09 06:26 UTC, dhruvinfo28 commented
@tarun26091999 I have made the requested changes , please review.

2021-03-10 08:55 UTC, raksha009 requested changes

2021-03-10 08:55 UTC, raksha009 commented on Code/C++/Kahns_algorithm.cpp
> +*/
Add an extra line here.

2021-03-10 08:55 UTC, raksha009 commented on Code/C++/Kahns_algorithm.cpp
> +    int in_degree[n]; //Array for keeping a track for indegree of all nodes
Add comments on top of the line.

2021-03-10 08:55 UTC, raksha009 commented on Code/C++/Kahns_algorithm.cpp
> +    vector <int> topological_order; //This vector will store the order
Add comments on top of the line.

2021-03-10 11:35 UTC, dhruvinfo28 commented
@raksha009 I have made the requested changes please review.

2021-03-10 16:06 UTC, raksha009 approved these changes
LGTM! 👍

2021-03-10 16:46 UTC, dhruvinfo28 commented
@tarun26091999 what am I missing? Is the link to the code file that I added broken?

2021-03-11 14:41 UTC, dhruvinfo28 commented
@tarun26091999 @raksha009  is the readme issue fixed now?

2021-03-12 20:14 UTC, tarun26091999 approved these changes
good

2021-03-12 20:15 UTC, merged