added display, change, getmin operations
Algo-Phantoms/Algo-Tree pull request #256
Opened 2021-03-09 03:54 UTC by mehak2323

Added the following stack operations:
-display() it prints all the elements available in the stack
-change(index,data) it changes the element at the given position
-getmin() returns the minimum element from Stack
and updated the test case.

2021-03-20 18:47 UTC, rudrakshi99 requested changes

2021-03-20 18:47 UTC, rudrakshi99 commented on Code/C++/stack_class.cpp
>  	Test Case :
add at least 2 test cases.

2021-03-30 10:01 UTC, mehak2323 commented
I've added a test case, please tell me any further changes. And when to update readme.

2021-04-02 15:33 UTC, tarun26091999 commented
@rudrakshi99 getmin() was not specified in the issue.

2021-04-02 15:40 UTC, rudrakshi99 commented
@mehak2323 Please remove getmin() function from your code as you have not mentioned it in your issue.

2021-04-05 14:02 UTC, mehak2323 commented
I have removed the getmin() function code now. Please let me know what I have to do next.

2021-04-19 17:24 UTC, rudrakshi99 commented
I think you have not removed it. Where is the commit?

2021-04-21 15:37 UTC, mehak2323 commented
Please check now.

2021-04-21 17:40 UTC, rudrakshi99 approved these changes

2021-04-21 17:41 UTC, merged