Added Bucket Sort (#147)
Algo-Phantoms/Algo-Tree pull request #288
Opened 2021-03-09 07:43 UTC by ShubhamGupta577

* **Adding Bucket Sort in C++**
* **Issue Resolved (#147 )**

2021-03-10 11:33 UTC, ShubhamGupta577 commented
@plazzy99 Please review this.

2021-03-10 14:12 UTC, plazzy99 requested changes
also, update the readme for the issue raised

2021-03-10 14:12 UTC, plazzy99 commented on Code/C++/Bucket Sort.cpp
> +#include <iostream>
add what is bubble sort at the top in multi-line comment

2021-03-10 14:12 UTC, plazzy99 commented on Code/C++/Bucket Sort.cpp
> +0.0476 0.1235 0.2045 0.2101 0.315 0.4142
time and space complexity must be added here.

2021-03-11 09:44 UTC, ShubhamGupta577 commented
@plazzy99 Requested Changes are done.

2021-03-16 06:01 UTC, plazzy99 reviewed
Readme needs to be updated for making this pr ready to merge

2021-03-16 07:38 UTC, ShubhamGupta577 commented
@plazzy99 . I am not getting that for which readme you are asking me to update.

2021-03-16 09:51 UTC, tarun26091999 commented
> @plazzy99 . I am not getting that for which readme you are asking me to update.

searching_sorting in the algorithm folder

2021-03-16 11:45 UTC, ShubhamGupta577 commented
@plazzy99 Thanks for the clarification, and the requested change has been made.

2021-03-19 22:49 UTC, ShubhamGupta577 commented
@plazzy99 Please have a review for this.

2021-04-13 19:51 UTC, tarun26091999 commented
conflicts still persist.

2021-04-13 20:55 UTC, ShubhamGupta577 commented
@tarun26091999 Please review it now.
Sorry for the inconvenience caused due to this.

2021-04-16 19:28 UTC, tarun26091999 commented
its not resolved yet.

2021-04-17 11:13 UTC, ShubhamGupta577 commented
@tarun26091999 . As I am new to open source contribution, that's why I am getting that what is the exact issue in this. Can you please help me to resolve this issue?

2021-05-02 22:20 UTC, yasharth291 commented
merging this will cause breaking changes @tarun26091999

2021-05-24 18:12 UTC, closed without merging