Added prime number code in cpp
Algo-Phantoms/Algo-Tree pull request #353
Opened 2021-03-09 16:31 UTC by soukarsha122

Issue #157 .
I added a code in C++ to check if a number is prime or not. The code even checks if the number inputted is integer or not as only positive integral numbers are in the set  of prime numbers. This is a small contribution on behalf of me for GSSOC'21.

2021-03-11 07:31 UTC, rudrakshi99 requested changes

2021-03-11 07:31 UTC, rudrakshi99 commented on prime number.cpp
> +  	int x=(int)N; // Variable to store the integer part of the inputted number
No need to typecast N. Just simply input integer value.

2021-03-11 07:31 UTC, rudrakshi99 commented on prime number.cpp
> +   Std    output: 11 is a prime number
Add time and space complexity at the end.

2021-03-11 07:32 UTC, rudrakshi99 commented
Also, add it to a proper folder.

2021-03-12 12:33 UTC, soukarsha122 commented
@rudrakshi99 can you please help me by saying how can i add my file to the C++ folder . Which git command do i have to use ? I am a beginner in git ,so I don't know all git commands .

2021-03-14 15:32 UTC, soukarsha122 commented
@rudrakshi99 @plazzy99 please review my code and tell me if any more changes needs to be done. I am very new to github and i faced difficulties while updating readme . Please tell me if anything is wrong.

2021-03-16 06:13 UTC, plazzy99 requested changes

2021-03-16 06:13 UTC, plazzy99 commented on Algorithm/Number_theory/readme.md
> -
you are strictly not allowed to delete any line written before.
Revert changes asap else your pr will be closed

2021-03-16 06:46 UTC, soukarsha122 commented
Please see now @plazzy99 . I have done as requested. Please tell me if I am wrong . Please tell me what further changes I need to do. Please merge this pr.

2021-03-31 08:51 UTC, soukarsha122 commented
@plazzy99 @rudrakshi99 @tarun26091999 please review my changes

2021-04-03 17:34 UTC, soukarsha122 commented
@raksha009  @shreyanspoddar please review my pr please merge it

2021-04-17 18:07 UTC, rudrakshi99 requested changes

2021-04-17 18:07 UTC, rudrakshi99 commented on Algorithm/Number_theory/readme.md
> +# Questions related to Number Theory
add one `#` also.

2021-04-18 03:31 UTC, soukarsha122 commented
@rudrakshi99 I have done the changes as requested.  Please tell me if any further changes needs to be done..
Please merge my pr..Thank you

2021-04-18 10:19 UTC, plazzy99 approved these changes

2021-04-18 10:20 UTC, merged