Bucket Sort using C++
Algo-Phantoms/Algo-Tree pull request #359
Opened 2021-03-09 16:43 UTC by EkjotKaur

Code for Bucket Sort in C++
with commented

- definition
- input and output
- time & space complexity

![bucketSort](https://user-images.githubusercontent.com/66993173/110505886-9693b380-8124-11eb-82b4-2c9fbce5a8db.png)

Fixed #124
Please view my PR @tarun26091999

2021-03-10 08:50 UTC, raksha009 requested changes
Read the guidelines as well and update the required readme (PS: not the main one).

2021-03-10 08:50 UTC, raksha009 commented on Code/C++/bucket_sort.cpp
> +
remove extra line

2021-03-10 08:50 UTC, raksha009 commented on Code/C++/bucket_sort.cpp
> +/*
Correct the indentation of the code and properly align it too.

2021-03-18 16:11 UTC, EkjotKaur commented
@tarun26091999 @nakul-19 @raksha009 please see this PR

2021-03-18 20:03 UTC, raksha009 requested changes

2021-03-18 20:03 UTC, raksha009 commented on Code/C++/bucket_sort.cpp
> +    Time Complexity:
Specify what is n and k

2021-03-18 20:03 UTC, raksha009 commented on Code/C++/bucket_sort.cpp
> +
Remove this extra line

2021-03-19 15:41 UTC, EkjotKaur commented
@tarun26091999 @nakul-19 @raksha009 please see this PR

2021-03-20 04:45 UTC, raksha009 commented
Use 4 space(a tab) indentation throughout,

2021-03-22 04:40 UTC, raksha009 requested changes
Plz use 4 space indentation everywhere

2021-03-22 05:48 UTC, EkjotKaur commented
I have used 4 space indentation everywhere.

2021-03-22 18:25 UTC, raksha009 requested changes

2021-03-22 18:25 UTC, raksha009 commented on Code/C++/bucket_sort.cpp
> +int maxValue(int A[], int n)
Add necessary comments everywhere - like what does this function do etc.

2021-03-22 18:25 UTC, raksha009 commented on Code/C++/bucket_sort.cpp
> +	int n;
Add comments.

2021-03-22 18:25 UTC, raksha009 commented on Code/C++/bucket_sort.cpp
> +              	4 63 1 53 87 44 36
Add 2 test cases

2021-03-24 04:28 UTC, anishsingh935 commented
HI can I implement the code of this problem with understandable comments??

2021-03-30 05:01 UTC, EkjotKaur commented
I was added all the suitable comments and 2 test cases
@raksha009 please merge this PR

2021-03-30 06:11 UTC, raksha009 approved these changes
LGTM 👍🏼

2021-04-02 16:33 UTC, EkjotKaur commented
@rudrakshi99 Please review my PR.

2021-04-04 05:11 UTC, EkjotKaur commented
@rudrakshi99 Please review my PR.

2021-04-05 16:09 UTC, einhawking commented
I am a participant of GSSOC'21
I would like to contribute in this

2021-04-07 15:30 UTC, EkjotKaur commented
@OjusWiZard  Please view this PR.

2021-04-16 15:12 UTC, merged