Added Brian Kernighan's algorithm.
Algo-Phantoms/Algo-Tree pull request #43
Opened 2021-02-18 16:52 UTC by debanjan-2002

Sir,
I have added Brian Kernighan's algorithm in the Bit Manipulation section. I have explained it very briefly and given the reasoning and intuition behind the algorithm. Please review my pull request, and if you like how I explain then please consider merging it.
I have also been selected in GSSOC'21, and I am really into DSA. So it would be a really kind of you if you give me the opportunity to contribute in this amazing repository.

Regards,
Debanjan Poddar

2021-03-06 10:07 UTC, debanjan-2002 commented
#44

2021-03-08 15:21 UTC, plazzy99 requested changes
Only 1 issue to be solved in one or

Remove Sieve code and add another for that

2021-03-08 15:21 UTC, plazzy99 commented on Code/C++/Brian_Kernighan.cpp
> +// Brian Kernighan's Algorithm
bring this comment on top of the file

2021-03-08 15:21 UTC, plazzy99 commented on Code/C++/Brian_Kernighan.cpp
> +    END...
Add time and space complexity

2021-03-08 15:22 UTC, plazzy99 commented
Also, update the readme file for that

2021-03-10 14:03 UTC, plazzy99 requested changes

2021-03-10 14:03 UTC, plazzy99 commented on Code/C++/Brian_Kernighan.cpp
> +/* It is an algorithm developed to count the number of set bits in a number
bring this comment outside the main code

2021-03-10 14:04 UTC, plazzy99 commented
Also please link your pr with the issue

2021-04-12 02:01 UTC, closed without merging