Add Bucket Sort
Algo-Phantoms/Algo-Tree pull request #471
Opened 2021-03-10 16:11 UTC by muthuannamalai12

I have added the code for Bucket Sort in java
Issue Number: #147

2021-03-16 03:45 UTC, muthuannamalai12 commented
@tarun26091999 please review this PR and please suggest the required changes.

2021-03-16 20:16 UTC, raksha009 requested changes

2021-03-16 20:16 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +Time Complexity:  O(n2)
Plz add a new line above.

2021-03-16 20:16 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +Time Complexity:  O(n2)
Write like n^2

2021-03-16 20:16 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +        for (int i=0; i<k; i++) {
Add changes around operator: like i = 0; i  < length; i++

2021-03-16 20:16 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +/*
Add a new line

2021-03-16 20:16 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +Sample input/output:-
Format it like Testcases

Input
Output

2021-03-16 20:16 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +Time Complexity:  O(n2)
Add a new line before Time Complexity.

2021-03-20 04:29 UTC, raksha009 requested changes

2021-03-20 04:29 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +        for (int i = 1; i<length; i++) {
Add space around the operators like <, =, > etc

2021-03-20 04:29 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +        for (int i=0; i<k; i++) {
Add space around the operators like <, =, > etc

2021-03-20 04:29 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +Test Cases:
Add 2 test cases

2021-03-20 04:29 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +Time Complexity:  O(n^2)
Mention what is n and k

2021-03-20 05:56 UTC, muthuannamalai12 commented
@raksha009 I have updated. Kindly review again

2021-03-22 04:38 UTC, raksha009 commented
Plz go through the guidelines and link yr code to appropriate folder.

2021-03-22 13:08 UTC, muthuannamalai12 commented
@raksha009 I have linked my code to the appropriate folder.

2021-03-22 18:29 UTC, raksha009 requested changes

2021-03-22 18:29 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +        for (int i = 1; i<length; i++) {
Add space around the operators like <
```suggestion
        for (int i = 1; i < length; i++) {
```

2021-03-22 18:29 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +        for (int i=0; i<k; i++) {
```suggestion
        for (int i = 0; i < k; i++) {
```

2021-03-23 04:50 UTC, muthuannamalai12 commented
@raksha009 I have made the requiered changes

2021-03-24 01:26 UTC, raksha009 requested changes

2021-03-24 01:26 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +Example 2:
```suggestion
Input:
```

2021-03-24 01:26 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +
Remove this extra line

2021-03-24 01:26 UTC, raksha009 commented on Code/Java/Bucket_Sort.java
> +
Remove extra line

2021-03-24 05:16 UTC, muthuannamalai12 commented
@raksha009 I have updated. Kindly review again

2021-03-26 18:28 UTC, raksha009 approved these changes
LBTM

2021-03-29 16:04 UTC, rudrakshi99 approved these changes

2021-03-29 16:04 UTC, merged