Create spiral_print.java
Algo-Phantoms/Algo-Tree pull request #475
Opened 2021-03-10 16:49 UTC by Arpit2401

2021-03-11 12:16 UTC, Arpit2401 commented
I am a GSSOC'21 participant and made this pull request. Please accept it amd merge it. Thanks!

2021-03-11 13:22 UTC, raksha009 requested changes
Plz follow consistent indentation throughout.

2021-03-11 13:22 UTC, raksha009 commented on Code/Java/spiral_print.java
> +import java.util.*;
Add a short description of the problem statement.

2021-03-11 13:22 UTC, raksha009 commented on Code/Java/spiral_print.java
> +	Test Cases :
add 2 test cases minimum

2021-03-11 13:22 UTC, raksha009 commented on Code/Java/spiral_print.java
> +
Remove extra line

2021-03-11 13:37 UTC, Arpit2401 commented
I have updated spiral_print.java with the required changes as asked by @raksha009. Do review it. Thanks!

2021-03-11 13:40 UTC, raksha009 requested changes

2021-03-11 13:40 UTC, raksha009 commented on Code/Java/spiral_print.java
> +    int sr = 0;
Inconsistent indentation.

2021-03-11 13:55 UTC, Arpit2401 commented
Indentation problem resolved. Do review it @raksha009

2021-03-11 18:29 UTC, raksha009 approved these changes

2021-03-12 16:10 UTC, Arpit2401 commented
@tarun26091999 sir please review my pr and do let me know if there are any changes.

2021-03-13 09:34 UTC, tarun26091999 requested changes
why you are trying to merge codes of spiral print and wave print by same PR. also issue is not linked to your PR.

2021-03-13 10:08 UTC, Arpit2401 commented
Sorry, @tarun26091999 sir wave print program was unknowingly added to this PR. I have removed that file. Also, my issue related to this PR is #616. Do let me know what has to be done now as I am a beginner in open source.

2021-03-14 19:29 UTC, tarun26091999 commented
you cannot raise a PR until the issue is assigned to you.

2021-03-14 19:29 UTC, closed without merging