Added Top_K_Frequent_Elements.java (#164)
Algo-Phantoms/Algo-Tree pull request #509
Opened 2021-03-10 19:10 UTC by sumitsantape30

Implemented the code of Top K Frequent Elements using Java.
#164
[x] - Code is well indented.
[x] - Code is well commented.
[x] - Code is not plagiarized.
[x] - Code is placed in the proper folder.
#GSSOC'21

2021-03-11 06:51 UTC, sumitsantape30 commented
@plazzy99  please review it.

2021-05-08 19:02 UTC, raksha009 requested changes

2021-05-08 19:02 UTC, raksha009 commented on Code/Java/Top_K_Frequent_Elements.java
> +		Scanner s= new Scanner(System.in);
Plz correct the indentation for line 23 and 24

2021-05-08 19:02 UTC, raksha009 commented on Code/Java/Top_K_Frequent_Elements.java
> +Space Complexity: O(n)
Specify n

2021-05-23 15:07 UTC, closed without merging