Create Doubly linked list
Algo-Phantoms/Algo-Tree pull request #574
Opened 2021-03-11 07:27 UTC by nandini040

Fixes #60
Added all the operations which can be performed on a doubly linked list using c++.

2021-03-11 07:42 UTC, nandini040 commented
@rudrakshi99 Review this issue and kindly ad `gssoc` and `level` label

2021-03-20 19:39 UTC, rudrakshi99 requested changes

2021-03-20 19:39 UTC, rudrakshi99 commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +#include <iostream>
add a brief description of the algorithm.

2021-03-20 19:39 UTC, rudrakshi99 commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +struct node
Don't use struct in c++. use class.

2021-03-20 19:39 UTC, rudrakshi99 commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +/* Time complexity:- O(1)
add it to the end.

2021-03-20 19:39 UTC, rudrakshi99 commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +/* Time complexity:- O(1)
add at the end.

2021-03-20 19:39 UTC, rudrakshi99 commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +/* Time complexity:- O(1)
add at the end.

2021-03-20 19:39 UTC, rudrakshi99 commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +*/
add at the end.

2021-03-20 19:39 UTC, rudrakshi99 commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +   Space complexity:- O(1)
add at the end.

2021-03-20 19:39 UTC, rudrakshi99 commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +*/
add at the end.

2021-03-20 19:39 UTC, rudrakshi99 commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +*/
add at the end.

2021-03-20 19:39 UTC, rudrakshi99 commented
Follow proper guidelines.

2021-03-22 08:37 UTC, nandini040 commented
@rudrakshi99 review the changes :)

2021-03-23 12:53 UTC, rudrakshi99 commented
Change `NULL` to `nullptr` in your code at every place.

2021-03-23 16:12 UTC, nandini040 commented
> Change `NULL` to `nullptr` in your code at every place.

@rudrakshi99 now is it okay?

2021-03-29 15:53 UTC, rudrakshi99 commented
add atleast 2 test cases for each operation at the end of the code but before the complexities.

2021-03-31 09:15 UTC, nandini040 commented
> add atleast 2 test cases for each operation at the end of the code but before the complexities.

For the test cases i have attached `README.md`

2021-04-04 10:16 UTC, rudrakshi99 commented
> > add atleast 2 test cases for each operation at the end of the code but before the complexities.
> 
> For the test cases i have attached `README.md`

No need to make a separate Readme for test cases. Just add the end to the code as per our guidelines.

2021-04-06 18:47 UTC, OjusWiZard requested changes
Add some inline comments in between your code to explain what small chunks of your code are doing.

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +   */
Shift complexities to the bottom of the main()

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +}
Add at least 2 input and output examples of this code before complexities (outside of the main())

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +   Space complexity:- O(1)
Complexities seem wrong

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +   Space complexity:- O(1)
Complexities seem wrong

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +}
No need to add this function

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +    }
This case will be the same as creating the first node because adding a node to the last of an empty list is the same as creating its first node.

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +        cout << "\nList is empty ";
In this case, if the index is 0, then the addition is possible just like creating the first node.

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +        ptr->next->prev = new_node;
Also, add a condition check above if the given index is more than the size of the Linked list. Else, a runtime error occurs here.

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +        free(last);
free the memory before assigning then the value of nullptr. Else, there will be a memory leak.

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +        ptr->next = nullptr;
Free the memory pointed by ptr.

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +        free(last);
free the memory before assigning then the value of nullptr. Else, there will be a memory leak.

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +        temp->prev = nullptr;
No need for this line.

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +    }
?????!

2021-04-06 18:47 UTC, OjusWiZard commented on Code/C++/Doubly_linkedlist/Doubly_linkedlist_all_operations.cpp
> +    {
Here also, add a similar check as before, i.e. index should not exceed the size of the list - 1.

2021-05-02 22:25 UTC, closed without merging