Tim sort in C++
Algo-Phantoms/Algo-Tree pull request #583
Opened 2021-03-11 08:34 UTC by Harikrishnan6336

Fixex  #415  in C++

2021-03-11 08:38 UTC, Harikrishnan6336 commented
Kindly review this PR @tarun26091999  @rudrakshi99

2021-03-16 09:50 UTC, Harikrishnan6336 commented
Kindly review this PR @raksha009

2021-03-16 14:15 UTC, raksha009 requested changes

2021-03-16 14:15 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +
Remove extra line

2021-03-16 14:15 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +    Time Complexity- O(n*log(n))
Write Time and Space complexity at the end.

2021-03-16 15:33 UTC, Harikrishnan6336 commented
@raksha009 I have made the suggested changes, Kindly review my PR.

2021-03-16 19:57 UTC, raksha009 requested changes

2021-03-16 19:57 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +
Remove this extra line.

2021-03-16 19:57 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +                                    (n-1)));
plz combine line 79 and 80.

2021-03-16 19:57 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +                            left += 2*size)
plz combine line 87 and 88.

2021-03-16 19:57 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +                                            (n-1));
plz combine line 93 and 94.

2021-03-16 19:57 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +Time Complexity- O(n*log(n))
Add time complexity and space complexity at end.

2021-03-16 19:57 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +SAMPLE INPUT AND OUTPUT
Donot write word Sample.

2021-03-17 04:31 UTC, Harikrishnan6336 commented
@raksha009  I have made the suggested changes, Kindly review my PR.

2021-03-17 16:06 UTC, raksha009 requested changes

2021-03-17 16:06 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +
Remove extra line

2021-03-17 16:06 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +            // Find thier mid point
sp. of their -- simply write "find mid point"

2021-03-17 16:06 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +1.
Write in format of input/ output

2021-03-17 16:06 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +Time Complexity- O(n*log(n))
Specify n

2021-03-17 16:07 UTC, raksha009 commented
> @anjul2000 @raksha009 I have made the suggested changes, Kindly review my PR. Also My issue was labelled with `gssoc21` and `Level2` labels could you also add these labels to my PR

Don't worry, we'll add the labels and tags before merging yr pr :)

2021-03-17 16:16 UTC, Harikrishnan6336 commented
I have made the required changes, Kindly review my PR @raksha009

2021-03-17 16:18 UTC, raksha009 requested changes

2021-03-17 16:18 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +        /* Shift elements of arr[0..i-1], that are
Reduce it to 2 line comment.

2021-03-17 16:20 UTC, raksha009 requested changes

2021-03-17 16:20 UTC, raksha009 commented on Code/C++/tim_sort.cpp
> +    for (int i = beg + 1; i <= end; i++)
use appropriate variable name, instead of beg, use start.

2021-03-17 18:59 UTC, raksha009 approved these changes
LGTM!👍

2021-03-18 13:20 UTC, Harikrishnan6336 commented
@tarun26091999 Kindly review my PR.

2021-03-20 18:21 UTC, rudrakshi99 approved these changes

2021-03-20 18:21 UTC, merged