Construction of binary tree from preorder and inorder traversal
Algo-Phantoms/Algo-Tree pull request #598
Opened 2021-03-11 10:00 UTC by aaadddiii

2021-03-11 13:32 UTC, raksha009 requested changes

2021-03-11 13:32 UTC, raksha009 commented on Tree/readme.md
plz remove this extra line.

2021-03-12 00:03 UTC, raksha009 approved these changes
LGTM!

2021-03-15 18:26 UTC, tarun26091999 requested changes
link the issue to your PR. Also use class instead of struct in C++. Also add the comments to explain the steps.

2021-03-15 18:27 UTC, tarun26091999 requested changes
also there should be atleast 2 testcases along with the space complexity

2021-03-16 06:37 UTC, tarun26091999 commented
you have to link your issue with the PR not your PR with the PR itself. Also resolve the conflict of the branch.

2021-03-16 08:38 UTC, tarun26091999 approved these changes

2021-03-16 08:39 UTC, merged