Added josephus problem recursive code in C++
Algo-Phantoms/Algo-Tree pull request #608
Opened 2021-03-11 11:39 UTC by abhishek7997

Added recursive code for Josephus Problem in C++.
Issue #442

2021-03-13 06:13 UTC, abhishek7997 commented
@tarun26091999 Please review my PR.

2021-03-28 15:03 UTC, tarun26091999 requested changes
link it to the folder. also add the explanation at the top.

2021-04-26 18:45 UTC, yasharth291 requested changes

2021-04-26 18:45 UTC, yasharth291 commented on Code/C++/josephus_problem.cpp
> +Input: 3,2
giving wrong output

2021-05-01 15:06 UTC, abhishek7997 commented on Code/C++/josephus_problem.cpp
> +Input: 3,2
I will check.

2021-05-01 17:19 UTC, closed without merging