Add Deletion of Alternate nodes in a linked list C++
Algo-Phantoms/Algo-Tree pull request #640
Opened 2021-03-11 15:15 UTC by Mohim-Singla

Adding program for deletion of alternate nodes of a linked list using c++

2021-04-02 15:34 UTC, rudrakshi99 requested changes

2021-04-02 15:34 UTC, rudrakshi99 commented on Code/C++/Deletion of Alternate nodes in a linked list.cpp
> +struct node{
use `class` instead of `struct`.

2021-04-02 15:34 UTC, rudrakshi99 reviewed
use `nullptr` instead of `NULL

2021-04-02 19:52 UTC, Mohim-Singla commented
@rudrakshi99  I have made the changes. Please check.

2021-04-03 16:57 UTC, rudrakshi99 approved these changes

2021-04-06 06:23 UTC, nakul-19 requested changes
@Mohim-Singla please make changes in the respective readme.

2021-04-06 10:55 UTC, Mohim-Singla commented
@nakul-19  Updated readme.md and resolved conflicts

2021-04-12 17:45 UTC, merged