Add Level Order Traversal For Binary Tree (C++)
Algo-Phantoms/Algo-Tree pull request #675
Opened 2021-03-11 18:38 UTC by AnjaliPatle

Closes #192

2021-03-20 19:09 UTC, rudrakshi99 requested changes

2021-03-20 19:09 UTC, rudrakshi99 commented on Code/C++/level_order_traversal_binary_tree.cpp
> +struct Node
Don't use struct in c++. Use class.

2021-03-20 19:09 UTC, rudrakshi99 commented on Code/C++/level_order_traversal_binary_tree.cpp
> +    return 0;
Add at least 2 test cases. Also, add time and space complexities.

2021-03-23 15:24 UTC, AnjaliPatle commented
Hey @rudrakshi99 , I've added testcases and time and space complexities. Please let me know if there are any more changes.

2021-03-25 17:31 UTC, rudrakshi99 commented
Add the 2 test cases in the comments also at the end with input and output. Do refer to our code folder, you will get an idea.

2021-03-25 17:32 UTC, rudrakshi99 requested changes

2021-03-25 17:32 UTC, rudrakshi99 commented on Code/C++/level_order_traversal_binary_tree.cpp
> +//LEVEL ORDER TRAVERSAL OF BINARY TREE
use multi comment.

2021-03-27 12:29 UTC, AnjaliPatle commented
@rudrakshi99  I've made the required changes.

2021-03-29 15:40 UTC, rudrakshi99 commented
Just replace `null` with `nullptr` then we are good to merge.

2021-04-01 11:11 UTC, AnjaliPatle commented
I have made the required changes. Kindly review it.

2021-04-03 15:16 UTC, OjusWiZard approved these changes

2021-04-03 15:58 UTC, rudrakshi99 approved these changes

2021-04-03 15:58 UTC, merged