Added the sudoku_solver problem in C++
Algo-Phantoms/Algo-Tree pull request #735
Opened 2021-03-12 08:11 UTC by noob-26

Added the Sudoku solver problem in C++ along with an explanation of the code, proper comments and sample input outputs.

Issue related to this PR #42

2021-03-12 14:27 UTC, raksha009 commented
Hey, plz do not create multiple issues for same pr.  I have changed the the title of that issue itself :)

2021-03-12 14:31 UTC, noob-26 commented
> Hey, plz do not create multiple issues for same pr. I have changed the the title of that issue itself :)

Maam, I created this PR for the Sudoku solver issue and I have also attached this PR to the issue. 
Issue #42

2021-03-12 14:33 UTC, raksha009 commented
> > Hey, plz do not create multiple issues for same pr. I have changed the the title of that issue itself :)
> 
> Maam, I created this PR for the Sudoku solver issue and I have also attached this PR to the issue.
> Issue #42

Don't worry, we have already acknowledged your Pr with the #42 issue. No need to create multiple issues for referencing the same pr.

2021-03-12 14:36 UTC, raksha009 reviewed
Plz link yr file to the resp. folder.

2021-03-12 14:36 UTC, raksha009 commented on Code/C++/sudoku_solver.cpp
> +
remove extra line

2021-03-12 14:36 UTC, raksha009 commented on Code/C++/sudoku_solver.cpp
> +
Remove extra line

2021-03-12 14:36 UTC, raksha009 commented on Code/C++/sudoku_solver.cpp
> +Time Complexity of the approach : O(9 ^ (N * N))
add time complexity at the end.

2021-03-12 14:56 UTC, noob-26 commented
I made the changes to the code and linked the code to the folder.

2021-03-12 15:07 UTC, raksha009 requested changes

2021-03-12 15:07 UTC, raksha009 commented on Algorithm/Backtracking/readme.md
> +
Remove extra line

2021-03-12 15:14 UTC, noob-26 commented on Algorithm/Backtracking/readme.md
> +
Made the change

2021-03-20 09:01 UTC, rudrakshi99 approved these changes

2021-03-21 08:03 UTC, raksha009 requested changes

2021-03-21 08:03 UTC, raksha009 commented on Code/C++/sudoku_solver.cpp
> +Space Complexity of the approach : O(N * N)
Specify n here

2021-03-21 10:48 UTC, raksha009 commented
Also, plz resolve merge conflicts!

2021-03-23 12:12 UTC, noob-26 commented
@raksha009 @rudrakshi99 I have made the change and resolved the merge conflict. Please review the changes I made.

2021-03-24 01:29 UTC, raksha009 approved these changes

2021-03-24 01:30 UTC, merged