Added the code for Linear Search (Python)
Algo-Phantoms/Algo-Tree pull request #746
Opened 2021-03-12 09:50 UTC by malavikarajeshvikraman

Hi, I have added the code for Linear Search in python ( Linear Search in Python #602 ) .
 Please review and merge it  @tarun26091999 .

2021-03-20 18:12 UTC, rudrakshi99 requested changes

2021-03-20 18:12 UTC, rudrakshi99 commented on Algorithm/Searching_Sorting/readme.md
> +* Unordered Linear Search ----> [Python](/Code/Python/linearsearch.py)
add this in the question section.

2021-03-20 18:12 UTC, rudrakshi99 commented on Code/Python/linearsearch.py
> +Test Case :
add at least 2 test cases.

2021-03-20 18:12 UTC, rudrakshi99 commented on Code/Python/linearsearch.py
> +
add space complexity also.

2021-03-21 12:03 UTC, malavikarajeshvikraman commented
@rudrakshi99  I have made the changes you requested. Please do merge it if its alright !

2021-03-24 18:17 UTC, tarun26091999 requested changes
space complexity is wrong. Add comments to explain the steps.

2021-03-29 15:56 UTC, rudrakshi99 approved these changes

2021-04-07 05:49 UTC, tarun26091999 approved these changes

2021-04-07 05:50 UTC, merged