Create Factorial_without_recursion.cpp
Algo-Phantoms/Algo-Tree pull request #748
Opened 2021-03-12 10:00 UTC by Subhangini

2021-04-10 18:25 UTC, Subhangini commented
@nakul- 19 and @rudrakshi99  please review it

2021-04-12 18:29 UTC, rudrakshi99 requested changes

2021-04-12 18:29 UTC, rudrakshi99 commented on Code/C++/Factorial_without_recursion.cpp
> +	Input : 5
add atleast 2 test cases

2021-04-12 18:30 UTC, rudrakshi99 commented
update the readme in the Number theory folder.

2021-04-13 11:00 UTC, Subhangini commented
ok

2021-04-13 11:57 UTC, Subhangini commented
made the changes .Review it

2021-04-16 14:56 UTC, rudrakshi99 requested changes

2021-04-16 14:56 UTC, rudrakshi99 commented on Code/C++/Factorial_without_recursion.cpp
> +/*
remove this opening and closing comment from here.

2021-04-17 13:09 UTC, Subhangini commented
done @rudrakshi99. sorry for the delay. Review the changes

2021-04-17 18:04 UTC, merged