Added repeating and missing number problem
Algo-Phantoms/Algo-Tree pull request #773
Opened 2021-03-12 14:27 UTC by chitrasingla

#317

2021-03-14 06:16 UTC, chitrasingla commented
@tarun26091999 merge this pr
#317 issue is assigned to me

2021-03-18 20:15 UTC, raksha009 requested changes

2021-03-18 20:15 UTC, raksha009 commented on Code/C++/repeating_and_missing_number.cpp
> +    int r=0,m=0;
Add spaces around the operators =,< etc

2021-03-18 20:15 UTC, raksha009 commented on Code/C++/repeating_and_missing_number.cpp
> +	Input :
Align testcases

2021-03-18 20:15 UTC, raksha009 commented on Code/C++/repeating_and_missing_number.cpp
> +	Time complexity : O(n)
Specify n

2021-03-20 04:41 UTC, raksha009 requested changes

2021-03-20 04:41 UTC, raksha009 commented on Code/C++/repeating_and_missing_number.cpp
> +    int n;
Specify what is n. Add appropriate comments everywhere.

2021-03-20 04:41 UTC, raksha009 commented on Code/C++/repeating_and_missing_number.cpp
> +    cout<<"Repeating number is "<<r<<endl;
Add space around the operatir  <<

2021-03-20 19:20 UTC, rudrakshi99 approved these changes

2021-03-21 10:46 UTC, raksha009 requested changes

2021-03-21 10:46 UTC, raksha009 commented on Code/C++/repeating_and_missing_number.cpp
> +    cout<<"Repeating number is "<<r<<endl;
Plz Add space around the operator <<

2021-03-22 18:11 UTC, raksha009 approved these changes

2021-03-22 18:13 UTC, merged