Adding splitting linked list program
Algo-Phantoms/Algo-Tree pull request #791
Opened 2021-03-12 16:12 UTC by Mohim-Singla

issue #687 

Adding program splitting liked list into two parts.

Please review it.

2021-04-02 16:17 UTC, rudrakshi99 reviewed
add necessary inline comments.

2021-04-02 16:17 UTC, rudrakshi99 commented on Code/C++/Splitting_Linked_lists.cpp
> +struct node* head=NULL;
use `class` instead of `struct`

2021-04-06 06:38 UTC, nakul-19 requested changes
@Mohim-Singla please make changes in respective readme.

2021-04-06 10:52 UTC, Mohim-Singla commented
@nakul-19 Updated readme.md file and resolved conflicts.

2021-04-12 17:54 UTC, rudrakshi99 commented
> add necessary inline comments and replace `NULL` with `nullptr`.

Do these changes also.

2021-04-12 19:46 UTC, Mohim-Singla commented
@rudrakshi99 done

2021-04-16 15:00 UTC, rudrakshi99 approved these changes

2021-04-16 15:00 UTC, merged