connected components in an undirected graph
Algo-Phantoms/Algo-Tree pull request #831
Opened 2021-03-13 07:01 UTC by veenit1802

I have completed the code for the connected components in an undirected graph. Kindly, please check if there is any problems.
@tarun26091999

2021-03-28 18:44 UTC, tarun26091999 requested changes
link it to the appropriate folder.

2021-03-28 18:44 UTC, tarun26091999 commented on Code/C++/connected_component_in_undirected_graph.cpp
> +    return ;
remove this line.

2021-04-07 15:03 UTC, veenit1802 reviewed
@tarun26091999 sir changes are made kindly check it

2021-04-20 11:30 UTC, veenit1802 commented
Sir, the conflict in the file is resolved, kindly check it. @tarun26091999

2021-05-04 15:59 UTC, tarun26091999 requested changes
remove -> sign after the last vertex of the component.

2021-05-24 18:24 UTC, closed without merging