N Queen Problem Code (C++)
Algo-Phantoms/Algo-Tree pull request #896
Opened 2021-03-13 19:11 UTC by AasthaSinha2305

I have added the code for n queen problem in backtracking section

- added the code in Code -> C++ folder.
- updated the backtracking readme
- commented each and every line properly
- 2 test cases added

issue #381

2021-03-14 21:17 UTC, raksha009 requested changes

2021-03-14 21:17 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +
Remove extra line

2021-03-14 21:17 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +                        whether it will be attacked by other queen or not,
press a tab(4 spaces to provide spaces here)

2021-03-14 21:17 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +
Remove extra line

2021-03-14 21:17 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +
Remove extra line

2021-03-14 21:17 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +
Remove extra line

2021-03-14 21:17 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +    //define n
Remove unnecessary comments

2021-03-14 21:17 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +
Remove extra line

2021-03-14 21:17 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +
Remove extra line

2021-03-14 21:17 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +
Add space complexity.

2021-03-14 21:17 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +/*
Include time and space complexity in same comment

2021-03-15 10:35 UTC, AasthaSinha2305 commented
@raksha009 I did the requested changes, please verify.

2021-03-16 20:30 UTC, raksha009 requested changes

2021-03-16 20:30 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +    while(x>=0 && y<n){
Add spaces around the operators like =, > , <

2021-03-16 20:30 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +        if(chessboard[x][y]==1){
Add spaces around the operators like ==

2021-03-16 20:30 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +    TEST CASE 1:
Plz align text along the horizontal.

2021-03-17 16:10 UTC, raksha009 requested changes

2021-03-17 16:10 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +//A queen is safe if there is not queen horizontally, verically and diagonal on both sides of eleements
Add a line after line 17

2021-03-17 16:10 UTC, raksha009 commented on Code/C++/n_queen_problem.cpp
> +TIME COMPLEXITY: O(N!)
Specify what is n

2021-03-20 17:08 UTC, AasthaSinha2305 commented
@raksha009 please verify this

2021-03-20 19:24 UTC, rudrakshi99 approved these changes

2021-03-21 10:38 UTC, raksha009 approved these changes
LGTM!

2021-03-21 10:40 UTC, merged