find first non-repeating character in a string in java  #569
Algo-Phantoms/Algo-Tree pull request #924
Opened 2021-03-14 06:30 UTC by ASLManasa

#569 Code using in java @tarun26091999  sir can you please merge it.

2021-04-09 10:06 UTC, ASLManasa commented
@raksha009 @shreyanspoddar  Sir Can you please review this code. Thank you. @tarun26091999

2021-04-09 10:09 UTC, ASLManasa commented
@raksha009 @shreyanspoddar  Sir Can you please review this code. Thank you. @tarun26091999

2021-04-14 14:34 UTC, raksha009 requested changes
Plz link yr code with the appropriate file. Go through the guidelines and pinned issues.

2021-04-14 14:40 UTC, raksha009 requested changes

2021-04-14 14:40 UTC, raksha009 commented on string/first_non_repeating_charachters
> +/* The program will find the first non-repeating character in the string if it is present in the string */
```suggestion
/* 
The program will find the first non-repeating character in the string if it is present in the string 
*/
```
Plz add a bit more detailed description here

2021-04-14 14:40 UTC, raksha009 commented on string/first_non_repeating_charachters
> +public class first_non_repeating_charachters {
```suggestion
public class first_non_repeating_characters {
```
Plz correct the spelling of character in file name too.

2021-04-14 14:40 UTC, raksha009 commented on string/first_non_repeating_charachters
> +    public static void non_repeating(String s) {
Add a newline above line 7

2021-04-14 14:40 UTC, raksha009 commented on string/first_non_repeating_charachters
> +        //calculating the frequency of the char
Add a newline above line 12

2021-04-14 14:40 UTC, raksha009 commented on string/first_non_repeating_charachters
> +
Remove like 21,22

2021-04-14 14:40 UTC, raksha009 commented on string/first_non_repeating_charachters
> +            //if the frequency of a char is 1 then print and stop the loop.
add this comment above line 14

2021-04-14 14:40 UTC, raksha009 commented on string/first_non_repeating_charachters
> +        //creating a scanner object
Remove this comment

2021-04-14 14:40 UTC, raksha009 commented on string/first_non_repeating_charachters
> +        //taking a string input and converting into lower case and removing trailing and leading spaces
Add a comment first above the line describing what the line is doing and then write that line

2021-04-14 14:40 UTC, raksha009 commented on string/first_non_repeating_charachters
> +1st testcase
Do not write 1st testcase and so on

2021-04-14 14:40 UTC, raksha009 commented on string/first_non_repeating_charachters
> +input: madam
```suggestion
Input: madam
```
Similarly O capital for Output

2021-04-20 04:29 UTC, ASLManasa commented
@raksha009  Mam I have made the changes If you check once I will make another pr . Thank you.

2021-04-20 11:56 UTC, raksha009 commented
Plz link yr code to the folder. Go through the guidlines and pinned issues.

2021-05-24 18:26 UTC, closed without merging