Binary Search in python
Algo-Phantoms/Algo-Tree pull request #947
Opened 2021-03-14 14:20 UTC by pallavidhere23

Issue #106 (binary search implementation) has solved here in python.

2021-03-20 19:34 UTC, rudrakshi99 requested changes

2021-03-20 19:34 UTC, rudrakshi99 commented on Code/Python/Binary_Search.py
> +x=int(input("Enter x"))
add a space after x.

2021-03-20 19:34 UTC, rudrakshi99 commented on Code/Python/Binary_Search.py
> +b=int(input("Enter Number to be Search"))
add space after Search

2021-03-20 19:34 UTC, rudrakshi99 commented on Code/Python/Binary_Search.py
> +    a.append(int(input("Enter next no:")))
add space after no.

2021-03-21 04:48 UTC, pallavidhere23 commented
@rudrakshi99 I have made all the required changes. Please review it.

2021-03-23 12:54 UTC, rudrakshi99 approved these changes

2021-03-23 12:54 UTC, rudrakshi99 commented
update the list in the sorting_searching folder.

2021-03-23 13:30 UTC, pallavidhere23 commented
[https://drive.google.com/file/d/1wJBhJX-o5LmRhYhopYgzI--uwtkmjLRw/view?usp=drivesdk](url) its already been updated according to the instruction given.

2021-03-23 13:33 UTC, pallavidhere23 commented
@rudrakshi99  Its already been updated you can see the files changed section of this pull request. I have added the Binary Search in readme of sorting_searching folder

2021-03-23 13:34 UTC, tarun26091999 requested changes
add comments in your code.

2021-03-23 13:56 UTC, pallavidhere23 commented
> add comments in your code.

@tarun26091999 I have added the comments ,Please review it.

2021-04-12 18:13 UTC, rudrakshi99 commented
Resolve the merge conflicts.

2021-04-15 06:13 UTC, pallavidhere23 commented
@rudrakshi99 , I have resolve the merge conflicts, kindly review it.

2021-04-16 15:02 UTC, merged